# Generated by GitHub Copilot
from langchain_google_genai import ChatGoogleGenerativeAI
from app.config import settings
from app.services.tools import tools
from app.utils.logger import logger

def get_llm():
    """
    Initialize and return the Google Gemini LLM.
    
    Returns:
        Configured ChatGoogleGenerativeAI instance
    
    Raises:
        ValueError: If GOOGLE_API_KEY is not configured
    """
    if not settings.GOOGLE_API_KEY:
        error_msg = "GOOGLE_API_KEY is not configured. Please set it in your .env file."
        logger.error(error_msg)
        raise ValueError(error_msg)
    
    try:
        llm = ChatGoogleGenerativeAI(
            model=settings.GEMINI_MODEL,
            google_api_key=settings.GOOGLE_API_KEY,
            temperature=settings.GEMINI_TEMPERATURE,
            max_tokens=settings.GEMINI_MAX_TOKENS,
            convert_system_message_to_human=True  # Gemini compatibility
        )
        logger.info(f"Initialized Gemini LLM: {settings.GEMINI_MODEL}")
        return llm
    except Exception as e:
        logger.error(f"Error initializing Gemini LLM: {e}")
        raise

def get_llm_with_tools():
    """
    Initialize LLM and bind tools for agentic behavior.
    Enables the LLM to use tools for data retrieval and actions.
    
    Returns:
        LLM instance with bound tools
    """
    try:
        llm = get_llm()
        llm_with_tools = llm.bind_tools(tools)
        logger.info(f"Bound {len(tools)} tools to LLM")
        return llm_with_tools
    except Exception as e:
        logger.error(f"Error binding tools to LLM: {e}")
        raise


