# Generated by GitHub Copilot
import json
import os
from datetime import datetime
from app.config import settings
from app.utils.logger import logger
from typing import List, Dict, Any, Optional


class JSONMemoryService:
    """
    JSON-based memory service for storing chat sessions and history.
    Provides thread-safe operations for session management.
    In future, this can be replaced with database storage.
    """
    
    def __init__(self, file_path: str = settings.MEMORY_STORAGE_PATH):
        self.file_path = file_path
        self._ensure_file_exists()

    def _ensure_file_exists(self):
        """Ensure the memory file and directory exist."""
        try:
            directory = os.path.dirname(self.file_path)
            if directory and not os.path.exists(directory):
                os.makedirs(directory, exist_ok=True)
            
            if not os.path.exists(self.file_path):
                with open(self.file_path, 'w', encoding='utf-8') as f:
                    json.dump({}, f)
                logger.info(f"Created new memory file at {self.file_path}")
        except Exception as e:
            logger.error(f"Error ensuring memory file exists: {e}")

    def save_chat(self, session_id: str, message: str, role: str):
        """
        Append a message to the session history in the JSON file.
        
        Args:
            session_id: Unique session identifier
            message: Message content
            role: Message role (user/assistant)
        """
        try:
            data = self._load_data()
            
            if session_id not in data:
                data[session_id] = {
                    "history": [],
                    "created_at": datetime.now().isoformat(),
                    "last_updated": datetime.now().isoformat()
                }
            
            data[session_id]["history"].append({
                "role": role,
                "content": message,
                "timestamp": datetime.now().isoformat()
            })
            data[session_id]["last_updated"] = datetime.now().isoformat()
            
            self._save_data(data)
            logger.debug(f"Saved {role} message to session {session_id}")
        except Exception as e:
            logger.error(f"Error saving chat message: {e}")

    def get_history(self, session_id: str) -> List[Dict[str, Any]]:
        """
        Retrieve chat history for a specific session.
        
        Args:
            session_id: Unique session identifier
        
        Returns:
            List of message dictionaries
        """
        data = self._load_data()
        return data.get(session_id, {}).get("history", [])

    def list_sessions(self) -> List[Dict[str, Any]]:
        """
        List all sessions with metadata.
        
        Returns:
            List of session info dictionaries
        """
        data = self._load_data()
        sessions = []
        
        for sid, info in data.items():
            sessions.append({
                "session_id": sid,
                "created_at": info.get("created_at", ""),
                "last_updated": info.get("last_updated", ""),
                "history_count": len(info.get("history", []))
            })
        
        # Sort by last_updated, most recent first
        sessions.sort(key=lambda x: x["last_updated"], reverse=True)
        return sessions

    def delete_session(self, session_id: str) -> bool:
        """
        Delete a specific session and its history.
        
        Args:
            session_id: Unique session identifier
        
        Returns:
            True if session was deleted, False if not found
        """
        try:
            data = self._load_data()
            
            if session_id in data:
                del data[session_id]
                self._save_data(data)
                logger.info(f"Deleted session {session_id}")
                return True
            else:
                logger.warning(f"Session {session_id} not found for deletion")
                return False
        except Exception as e:
            logger.error(f"Error deleting session: {e}")
            return False

    def clear_old_sessions(self, days: int = 30) -> int:
        """
        Clear sessions older than specified days.
        
        Args:
            days: Age threshold in days
        
        Returns:
            Number of sessions deleted
        """
        try:
            data = self._load_data()
            current_time = datetime.now()
            deleted_count = 0
            
            sessions_to_delete = []
            for sid, info in data.items():
                last_updated = datetime.fromisoformat(info.get("last_updated", ""))
                age_days = (current_time - last_updated).days
                
                if age_days > days:
                    sessions_to_delete.append(sid)
            
            for sid in sessions_to_delete:
                del data[sid]
                deleted_count += 1
            
            if deleted_count > 0:
                self._save_data(data)
                logger.info(f"Cleared {deleted_count} old sessions")
            
            return deleted_count
        except Exception as e:
            logger.error(f"Error clearing old sessions: {e}")
            return 0

    def _load_data(self) -> Dict[str, Any]:
        """Load data from JSON file."""
        try:
            with open(self.file_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except FileNotFoundError:
            self._ensure_file_exists()
            return {}
        except json.JSONDecodeError:
            logger.error("Invalid JSON in memory file, returning empty dict")
            return {}
        except Exception as e:
            logger.error(f"Error loading memory: {e}")
            return {}

    def _save_data(self, data: Dict[str, Any]):
        """Save data to JSON file."""
        try:
            with open(self.file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
        except Exception as e:
            logger.error(f"Error saving memory: {e}")


# Global singleton instance
memory_service = JSONMemoryService()
