# Generated by GitHub Copilot
"""Short-term memory service (MySQL-backed).

This service stores per-session chat history and the rolling short-term
summary. It is a thin facade over :mod:`app.repositories.short_term_repo`,
preserving the exact public API the rest of the app already depends on
(``save_chat``, ``get_history``, ``list_sessions``, ``delete_session``,
``clear_old_sessions``, ``get_summary``, ``save_summary``) so no call sites
needed to change when migrating from JSON files to MySQL.

The legacy JSON implementation is preserved (commented out) at the bottom of
this file for reference.
"""

from typing import List, Dict, Any, Optional

from app.repositories import short_term_repo


class SQLMemoryService:
    """MySQL-backed memory service for chat sessions and history."""

    def save_chat(
        self, session_id: str, message: str, role: str, client_id: Optional[str] = None
    ) -> None:
        """Append a message to the session history.

        Args:
            session_id: Unique session identifier.
            message:    Message content.
            role:       Message role (``user`` / ``assistant``).
            client_id:  Owning client (from request metadata); stamps the
                        session so chat history can be traced to a client.
        """
        short_term_repo.save_message(session_id, role, message, client_id=client_id)

    def get_history(self, session_id: str) -> List[Dict[str, Any]]:
        """Return chat history (chronological) for a session.

        Each item: ``{"role", "content", "timestamp"}``.
        """
        return short_term_repo.get_history(session_id)

    def list_sessions(self, client_id: Optional[str] = None) -> List[Dict[str, Any]]:
        """List sessions with metadata, most-recent first.

        Args:
            client_id: When provided, only that client's sessions are returned.
        """
        return short_term_repo.list_sessions(client_id=client_id)

    def delete_session(self, session_id: str) -> bool:
        """Delete a session and its history. Returns ``True`` if it existed."""
        return short_term_repo.delete_session(session_id)

    def clear_old_sessions(self, days: int = 30) -> int:
        """Delete sessions older than *days*. Returns the number removed."""
        return short_term_repo.clear_old_sessions(days)

    def get_summary(self, session_id: str) -> Optional[str]:
        """Return the rolling short-term summary for a session, or ``None``."""
        return short_term_repo.get_summary(session_id)

    def save_summary(self, session_id: str, summary: str) -> None:
        """Persist the rolling short-term summary for a session."""
        short_term_repo.save_summary(session_id, summary)


# Global singleton instance (DB-backed) — same name/API as before.
memory_service = SQLMemoryService()


# ══════════════════════════════════════════════════════════════════════════════
# LEGACY JSON IMPLEMENTATION — DISABLED (kept for reference only)
# ══════════════════════════════════════════════════════════════════════════════
# The class below stored sessions in a JSON file (data/memory/sessions.json).
# It has been replaced by SQLMemoryService above and is intentionally commented
# out so the JSON storage code no longer runs.
#
# import json
# import os
# from datetime import datetime
# from app.config import settings
#
#
# class JSONMemoryService:
#     """
#     JSON-based memory service for storing chat sessions and history.
#     Provides thread-safe operations for session management.
#     """
#
#     def __init__(self, file_path: str = settings.MEMORY_STORAGE_PATH):
#         self.file_path = file_path
#         self._ensure_file_exists()
#
#     # The full JSON implementation (save_chat / get_history / list_sessions /
#     # delete_session / clear_old_sessions / get_summary / save_summary plus the
#     # private _ensure_file_exists / _load_data / _save_data helpers) read and
#     # wrote data/memory/sessions.json. All of that JSON storage logic is now
#     # disabled — the SQLMemoryService above persists the same data in MySQL via
#     # app.repositories.short_term_repo. The original code remains available in
#     # version control if a reference is ever needed.
#
#
# # Global singleton instance (legacy)
# memory_service = JSONMemoryService()
