# Generated by GitHub Copilot
"""SQLAlchemy ORM models for the memory database (MySQL).

Two memory tiers are modelled here:

Short-term memory (per *session*)
---------------------------------
``chat_sessions``   One row per chat session. Holds the rolling short-term
                    summary and bookkeeping timestamps.
``chat_messages``   One row per user/assistant message, ordered by
                    ``created_at`` so Q&A turns can be reconstructed in time
                    order for the LLM context window.

Long-term memory (per *client*, across all sessions)
----------------------------------------------------
``episodic_memory``    One row per completed Q&A turn → "what we discussed".
``semantic_memory``    Durable extracted facts about the client → "client model".
``procedural_memory``  Observed behavioural/communication patterns + frequency.
``client_preferences`` Durable, structured client preferences (key→value) →
                       risk tolerance, communication channel, investment style.

Every short-term session AND every long-term record carries a ``client_id`` so
any conversation or memory can be traced back to the client it belongs to.
All timestamps are stored in UTC. ``client_id`` columns are indexed so every
lookup is scoped efficiently to a single client.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Declarative base for all memory ORM models."""


# ══════════════════════════════════════════════════════════════════════════════
# Short-term memory
# ══════════════════════════════════════════════════════════════════════════════

class ChatSession(Base):
    """A single chat session and its rolling short-term summary."""

    __tablename__ = "chat_sessions"

    session_id: Mapped[str] = mapped_column(String(100), primary_key=True)
    # Client this session belongs to ("unknown" when no client was selected).
    # Lets every session — and, by FK, every message — be traced to a client.
    client_id: Mapped[str] = mapped_column(
        String(64), nullable=False, default="unknown", server_default="unknown", index=True
    )
    # Rolling LLM summary of older turns (short-term memory compression).
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
    last_updated: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    messages: Mapped[list["ChatMessage"]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="ChatMessage.created_at",
        lazy="selectin",
    )

    __table_args__ = (
        # List a client's sessions newest-first.
        Index("ix_chat_sessions_client_updated", "client_id", "last_updated"),
    )


class ChatMessage(Base):
    """One message (user or assistant) within a chat session."""

    __tablename__ = "chat_messages"

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    session_id: Mapped[str] = mapped_column(
        String(100),
        ForeignKey("chat_sessions.session_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False)  # user | assistant
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), index=True
    )

    session: Mapped["ChatSession"] = relationship(back_populates="messages")

    __table_args__ = (
        # Time-ordered retrieval of a session's turns.
        Index("ix_chat_messages_session_created", "session_id", "created_at"),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Long-term memory — episodic
# ══════════════════════════════════════════════════════════════════════════════

class EpisodicMemory(Base):
    """One completed Q&A turn for a client (recallable across sessions)."""

    __tablename__ = "episodic_memory"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)  # uuid4
    client_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    session_id: Mapped[str] = mapped_column(String(100), nullable=False)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    intent: Mapped[str] = mapped_column(String(64), nullable=False)
    confidence: Mapped[float] = mapped_column(Numeric(5, 3), nullable=False, default=1.0)
    # JSON-encoded embedding of the query — powers semantic episodic recall.
    embedding: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), index=True
    )

    __table_args__ = (
        # Pull the most-recent episodes for a client quickly.
        Index("ix_episodic_client_created", "client_id", "created_at"),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Long-term memory — semantic
# ══════════════════════════════════════════════════════════════════════════════

class SemanticMemory(Base):
    """A durable, deduplicated fact about a client."""

    __tablename__ = "semantic_memory"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)  # uuid4
    client_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    fact: Mapped[str] = mapped_column(Text, nullable=False)
    # SHA-256 of the normalised (lower-cased, trimmed) fact — enables a DB-level
    # uniqueness guarantee for deduplication without an index on a TEXT column.
    fact_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    confidence: Mapped[float] = mapped_column(Numeric(5, 3), nullable=False, default=0.85)
    source_query: Mapped[str] = mapped_column(String(500), nullable=False, default="")
    # JSON-encoded embedding of the fact — powers semantic retrieval and
    # near-duplicate reconciliation (update-in-place instead of append).
    embedding: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), index=True
    )

    __table_args__ = (
        UniqueConstraint("client_id", "fact_hash", name="uq_semantic_client_fact"),
        Index("ix_semantic_client_created", "client_id", "created_at"),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Long-term memory — procedural
# ══════════════════════════════════════════════════════════════════════════════

class ProceduralMemory(Base):
    """An observed behavioural/communication pattern, with a frequency counter."""

    __tablename__ = "procedural_memory"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)  # uuid4
    client_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    pattern: Mapped[str] = mapped_column(Text, nullable=False)
    # SHA-256 of the normalised pattern — used to upsert the frequency counter.
    pattern_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    frequency: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
    last_seen: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        UniqueConstraint("client_id", "pattern_hash", name="uq_procedural_client_pattern"),
        Index("ix_procedural_client_freq", "client_id", "frequency"),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Long-term memory — preferences
# ══════════════════════════════════════════════════════════════════════════════

class ClientPreference(Base):
    """A durable, structured preference for a client (one row per key).

    Preferences are the *actionable* slice of long-term memory: risk
    tolerance, preferred communication channel, reporting cadence, investment
    style, sector interests, etc. Unlike free-text semantic facts, each
    preference is a ``key → value`` pair so it can be looked up and updated
    deterministically (an updated value overwrites the old one).
    """

    __tablename__ = "client_preferences"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)  # uuid4
    client_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # Grouping bucket: 'risk' | 'investment' | 'communication' | 'general'.
    category: Mapped[str] = mapped_column(String(64), nullable=False, default="general")
    # Stable preference name, e.g. 'risk_tolerance', 'preferred_channel'.
    pref_key: Mapped[str] = mapped_column(String(100), nullable=False)
    pref_value: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Numeric(5, 3), nullable=False, default=0.8)
    # How the preference was captured: 'explicit' (user stated) | 'inferred'.
    source: Mapped[str] = mapped_column(String(20), nullable=False, default="inferred")
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        # One value per (client, key); upserts overwrite the existing value.
        UniqueConstraint("client_id", "pref_key", name="uq_pref_client_key"),
        Index("ix_pref_client_category", "client_id", "category"),
    )
