# Generated by GitHub Copilot
"""SQLAlchemy engine and session management for the memory database.

A single process-wide engine with connection pooling is created from
``settings.MEMORY_DATABASE_URL`` (MySQL via PyMySQL). All repository code
acquires short-lived sessions through the :func:`session_scope` context
manager, which guarantees commit-on-success / rollback-on-error / always-close.
"""

from __future__ import annotations

from contextlib import contextmanager
from typing import Iterator

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import Session, sessionmaker

from app.config import settings
from app.db.models import Base
from app.utils.logger import logger

# ── Engine ─────────────────────────────────────────────────────────────────────
# pool_pre_ping  → transparently recycles connections dropped by MySQL.
# pool_recycle   → proactively refresh connections older than 1 hour
#                  (avoids MySQL "server has gone away" on idle pools).
engine = create_engine(
    settings.MEMORY_DATABASE_URL,
    pool_pre_ping=True,
    pool_recycle=3600,
    pool_size=10,
    max_overflow=20,
    echo=settings.DB_ECHO,
    future=True,
)

# ── Session factory ────────────────────────────────────────────────────────────
SessionLocal = sessionmaker(
    bind=engine,
    autoflush=False,
    expire_on_commit=False,
    future=True,
)


@contextmanager
def session_scope() -> Iterator[Session]:
    """Provide a transactional scope around a series of operations.

    Commits on success, rolls back on any exception, and always closes the
    session. Use as::

        with session_scope() as db:
            db.add(obj)
    """
    session = SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def init_db() -> None:
    """Create all memory tables if they do not already exist.

    Idempotent — safe to call on every application startup. Does **not** drop
    or alter existing tables, except for additive column migrations handled by
    :func:`_ensure_columns` (adds the ``embedding`` columns to pre-existing
    long-term memory tables).
    """
    Base.metadata.create_all(bind=engine)
    _ensure_columns()
    logger.info("init_db: memory tables ensured (PostgreSQL)")


def _ensure_columns() -> None:
    """Additively migrate pre-existing tables (add missing ``embedding`` columns).

    Safe and idempotent: only issues ``ALTER TABLE ... ADD COLUMN`` when a table
    already exists and the column is absent. New databases get the column from
    ``create_all`` and skip this entirely. Never raises.
    """
    wanted = {
        "episodic_memory": "embedding",
        "semantic_memory": "embedding",
    }
    try:
        inspector = inspect(engine)
        existing_tables = set(inspector.get_table_names())
        for table, column in wanted.items():
            if table not in existing_tables:
                continue
            cols = {c["name"] for c in inspector.get_columns(table)}
            if column in cols:
                continue
            with engine.begin() as conn:
                # PostgreSQL supports ADD COLUMN IF NOT EXISTS (pg 9.6+)
                conn.execute(text(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} TEXT"))
                # MYSQL_DISABLED — was: ALTER TABLE {table} ADD COLUMN {column} TEXT
            logger.info(f"_ensure_columns: added {table}.{column}")
    except Exception as e:  # pragma: no cover - depends on live DB
        logger.warning(f"_ensure_columns: migration skipped ({type(e).__name__}: {e})")


def ping_db() -> bool:
    """Return ``True`` if the database accepts a trivial ``SELECT 1``.

    Used by the health-check endpoint. Never raises — returns ``False`` on any
    connection error.
    """
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception as e:  # pragma: no cover - depends on live DB
        logger.warning(f"ping_db: database unreachable ({type(e).__name__}: {e})")
        return False
