# Generated by GitHub Copilot
"""
Common utility functions for the Wealth Management Assistant.
Provides reusable helper functions for validation, formatting, and data processing.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
import re
import json
from decimal import Decimal


def format_currency(amount: float, currency: str = "INR", symbol: str = "\u20b9") -> str:
    """
    Format a number as currency with proper thousand separators.
    
    Args:
        amount: The amount to format
        currency: Currency code (default: INR)
        symbol: Currency symbol (default: ₹)
    
    Returns:
        Formatted currency string
    """
    return f"{symbol}{amount:,.2f}"


def validate_session_id(session_id: str) -> bool:
    """
    Validate session ID format.
    Must be alphanumeric with optional hyphens/underscores.
    
    Args:
        session_id: Session ID to validate
    
    Returns:
        True if valid, False otherwise
    """
    if not session_id or len(session_id) > 100:
        return False
    return bool(re.match(r'^[a-zA-Z0-9_-]+$', session_id))


def sanitize_input(text: str, max_length: int = 5000) -> str:
    """
    Sanitize user input by removing potentially harmful characters.
    
    Args:
        text: Input text to sanitize
        max_length: Maximum allowed length
    
    Returns:
        Sanitized text
    """
    if not text:
        return ""
    
    # Truncate to max length
    text = text[:max_length]
    
    # Remove control characters except newlines and tabs
    text = re.sub(r'[\x00-\x08\x0b-\x0c\x0e-\x1f\x7f]', '', text)
    
    return text.strip()


def extract_keywords(text: str) -> List[str]:
    """
    Extract keywords from text for routing and analysis.
    
    Args:
        text: Input text
    
    Returns:
        List of extracted keywords
    """
    # Simple keyword extraction (can be enhanced with NLP)
    words = re.findall(r'\b\w+\b', text.lower())
    
    # Filter out common stop words
    stop_words = {'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'is', 'are', 'was', 'were'}
    keywords = [word for word in words if word not in stop_words and len(word) > 2]
    
    return list(set(keywords))


def calculate_percentage_change(old_value: float, new_value: float) -> float:
    """
    Calculate percentage change between two values.
    
    Args:
        old_value: Original value
        new_value: New value
    
    Returns:
        Percentage change
    """
    if old_value == 0:
        return 0.0
    return ((new_value - old_value) / old_value) * 100


def format_timestamp(timestamp: Optional[str] = None) -> str:
    """
    Format timestamp for consistent display.
    
    Args:
        timestamp: ISO format timestamp string. If None, uses current time.
    
    Returns:
        Formatted timestamp string
    """
    if timestamp:
        dt = datetime.fromisoformat(timestamp)
    else:
        dt = datetime.now()
    
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def deep_merge_dicts(dict1: Dict[str, Any], dict2: Dict[str, Any]) -> Dict[str, Any]:
    """
    Deep merge two dictionaries.
    
    Args:
        dict1: First dictionary
        dict2: Second dictionary (takes precedence)
    
    Returns:
        Merged dictionary
    """
    result = dict1.copy()
    
    for key, value in dict2.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = deep_merge_dicts(result[key], value)
        else:
            result[key] = value
    
    return result


def safe_json_loads(json_str: str, default: Any = None) -> Any:
    """
    Safely parse JSON string with fallback.
    
    Args:
        json_str: JSON string to parse
        default: Default value if parsing fails
    
    Returns:
        Parsed JSON or default value
    """
    try:
        return json.loads(json_str)
    except (json.JSONDecodeError, TypeError, ValueError):
        return default if default is not None else {}


def truncate_text(text: str, max_length: int = 100, suffix: str = "...") -> str:
    """
    Truncate text to specified length with suffix.
    
    Args:
        text: Text to truncate
        max_length: Maximum length
        suffix: Suffix to append if truncated
    
    Returns:
        Truncated text
    """
    if len(text) <= max_length:
        return text
    return text[:max_length - len(suffix)] + suffix


def get_nested_value(data: Dict[str, Any], path: str, default: Any = None) -> Any:
    """
    Get value from nested dictionary using dot notation.
    
    Args:
        data: Dictionary to search
        path: Dot-separated path (e.g., "user.profile.name")
        default: Default value if path not found
    
    Returns:
        Value at path or default
    """
    keys = path.split('.')
    value = data
    
    try:
        for key in keys:
            value = value[key]
        return value
    except (KeyError, TypeError, IndexError):
        return default
