# Generated by GitHub Copilot
import logging
import sys
import os
from logging.handlers import RotatingFileHandler
from app.config import settings
from pathlib import Path

def setup_logger(name: str, log_file: str = None) -> logging.Logger:
    """
    Setup a comprehensive logger with console and file handlers.
    Includes rotation to prevent log files from growing too large.
    
    Args:
        name: Logger name
        log_file: Optional log file path. If None, uses settings.LOG_FILE
    
    Returns:
        Configured logger instance
    """
    logger = logging.getLogger(name)
    logger.setLevel(getattr(logging, settings.LOG_LEVEL.upper(), logging.INFO))

    # Prevent duplicate handlers
    if logger.handlers:
        return logger

    # Formatter with detailed information
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )

    # Console handler
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(formatter)
    console_handler.setLevel(logging.INFO)
    logger.addHandler(console_handler)

    # File handler with rotation (if enabled)
    if settings.ENABLE_FILE_LOGGING:
        try:
            log_path = log_file or settings.LOG_FILE
            log_dir = os.path.dirname(log_path)
            
            # Create log directory if it doesn't exist
            if log_dir and not os.path.exists(log_dir):
                os.makedirs(log_dir, exist_ok=True)
            
            # Rotating file handler (10MB per file, keep 5 backups)
            file_handler = RotatingFileHandler(
                log_path,
                maxBytes=10 * 1024 * 1024,  # 10MB
                backupCount=5,
                encoding='utf-8'
            )
            file_handler.setFormatter(formatter)
            file_handler.setLevel(logging.DEBUG)
            logger.addHandler(file_handler)
        except Exception as e:
            logger.warning(f"Could not setup file logging: {e}")

    return logger

# Create a default logger for the application
logger = setup_logger("WMA-App")

