# Generated by GitHub Copilot
"""Agent memory subpackage.

Holds long-term memory (episodic / semantic / procedural / preferences) used
by the Wealth Management agents. Short-term (per-session) memory remains a
generic persistence service under ``app.services.memory``.
"""
