"""Prompt package — active prompts for each agent."""

from app.prompts.memory import MEMORY_EXTRACTION_PROMPT
from app.prompts.portfolio_insights import (
    PORTFOLIO_INSIGHTS_SYSTEM_PROMPT,
    PORTFOLIO_INSIGHTS_USER_TEMPLATE,
    PORTFOLIO_TOOL_COLLECTION_SUFFIX,
)
from app.prompts.relationship_intelligence import (
    CRM_TOOL_COLLECTION_SUFFIX,
    RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT,
    RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE,
)
from app.prompts.router import ROUTER_SYSTEM_PROMPT, ROUTER_USER_TEMPLATE
from app.prompts.synthesizer import (
    SYNTHESIZER_CLARIFICATION_TEMPLATE,
    SYNTHESIZER_SYSTEM_PROMPT,
    SYNTHESIZER_USER_TEMPLATE,
)

__all__ = [
    "MEMORY_EXTRACTION_PROMPT",
    "PORTFOLIO_INSIGHTS_SYSTEM_PROMPT",
    "PORTFOLIO_INSIGHTS_USER_TEMPLATE",
    "PORTFOLIO_TOOL_COLLECTION_SUFFIX",
    "CRM_TOOL_COLLECTION_SUFFIX",
    "RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT",
    "RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE",
    "ROUTER_SYSTEM_PROMPT",
    "ROUTER_USER_TEMPLATE",
    "SYNTHESIZER_CLARIFICATION_TEMPLATE",
    "SYNTHESIZER_SYSTEM_PROMPT",
    "SYNTHESIZER_USER_TEMPLATE",
]
