# Generated by GitHub Copilot
"""Prompt package for the Wealth Management Assistant — Helix.

Prompts are split into one module per agent for maintainability:

    portfolio_insights        → PORTFOLIO_INSIGHTS_SYSTEM_PROMPT / _USER_TEMPLATE
    relationship_intelligence → RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT / _USER_TEMPLATE
    general                   → GENERAL_SYSTEM_PROMPT / _USER_TEMPLATE
    clarification             → CLARIFICATION_SYSTEM_PROMPT / _USER_TEMPLATE
    router                    → ROUTER_SYSTEM_PROMPT / _USER_TEMPLATE
    orchestrator              → ORCHESTRATOR_SYSTEM_PROMPT

Everything is re-exported here so callers may import either from the specific
module (preferred) or from ``app.prompts`` directly.
"""

from app.prompts.clarification import (
    CLARIFICATION_SYSTEM_PROMPT,
    CLARIFICATION_USER_TEMPLATE,
)
from app.prompts.general import GENERAL_SYSTEM_PROMPT, GENERAL_USER_TEMPLATE
from app.prompts.orchestrator import ORCHESTRATOR_SYSTEM_PROMPT
from app.prompts.portfolio_insights import (
    PORTFOLIO_INSIGHTS_SYSTEM_PROMPT,
    PORTFOLIO_INSIGHTS_USER_TEMPLATE,
)
from app.prompts.relationship_intelligence import (
    RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT,
    RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE,
)
from app.prompts.router import ROUTER_SYSTEM_PROMPT, ROUTER_USER_TEMPLATE

__all__ = [
    "PORTFOLIO_INSIGHTS_SYSTEM_PROMPT",
    "PORTFOLIO_INSIGHTS_USER_TEMPLATE",
    "RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT",
    "RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE",
    "GENERAL_SYSTEM_PROMPT",
    "GENERAL_USER_TEMPLATE",
    "CLARIFICATION_SYSTEM_PROMPT",
    "CLARIFICATION_USER_TEMPLATE",
    "ROUTER_SYSTEM_PROMPT",
    "ROUTER_USER_TEMPLATE",
    "ORCHESTRATOR_SYSTEM_PROMPT",
]
