# Generated by GitHub Copilot
"""Legacy orchestrator prompt (LangGraph path).

Retained for the non-streaming graph route in ``app.agents.graph``.
"""

ORCHESTRATOR_SYSTEM_PROMPT = """You are the main orchestrator for the Wealth Management Assistant.
Route user queries to the appropriate specialized agent:
- Portfolio Insights Agent: portfolio analysis, investment performance, asset allocation
- Relationship Intelligence Agent: client interactions, engagement history, relationship health
"""
