# Generated by GitHub Copilot
import os
from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Optional

class Settings(BaseSettings):
    """
    Application settings for Wealth Management Assistant.
    Loaded from environment variables or .env file.
    All settings are easily configurable and can be overridden.
    """
    # Application Info
    APP_NAME: str = "Wealth Management Assistant"
    API_V1_STR: str = "/api/v1"
    VERSION: str = "1.0.0"
    DESCRIPTION: str = "Agentic RAG-powered Wealth Management Assistant using LangGraph"
    
    # Server Settings
    HOST: str = "0.0.0.0"  # Listen on all interfaces - access via localhost or IP
    PORT: int = 8000
    DEBUG: bool = True
    RELOAD: bool = True  # Auto-reload on code changes

    # Google Gemini LLM Settings
    GOOGLE_API_KEY: Optional[str] = os.getenv("GOOGLE_API_KEY")
    GEMINI_MODEL: str = "gemini-1.5-pro"
    GEMINI_TEMPERATURE: float = 0.7
    GEMINI_MAX_TOKENS: int = 8192

    # Memory Settings
    MEMORY_STORAGE_PATH: str = "data/memory/sessions.json"
    
    # Logging Configuration
    LOG_LEVEL: str = "INFO"
    ENABLE_FILE_LOGGING: bool = True
    LOG_FILE: str = "logs/app.log"

    # CORS Settings (if needed in future)
    BACKEND_CORS_ORIGINS: list = ["*"]
    
    # Agent Configuration
    DEFAULT_AGENT_TIMEOUT: int = 30  # seconds
    MAX_AGENT_ITERATIONS: int = 5

    model_config = SettingsConfigDict(
        env_file=".env", 
        env_file_encoding='utf-8',
        case_sensitive=True,
        extra='ignore'
    )

settings = Settings()

