# Generated by GitHub Copilot
"""Agents package for the Wealth Management Assistant.

Layout (one concern per module):

    base                       → shared LLM singleton + history helpers (BaseAgent)
    state                      → AgentState TypedDict
    router                     → RouterAgent (intent classification)
    portfolio_insights         → PortfolioInsightsAgent
    relationship_intelligence  → RelationshipIntelligenceAgent
    general                    → GeneralAgent
    clarification              → ClarificationAgent
    graph                      → LangGraph wiring (non-streaming REST path)
    orchestrator               → process_chat / stream_agent entry points
    memory.long_term_memory    → episodic / semantic / procedural / preferences
"""

from app.agents.orchestrator import process_chat, stream_agent

__all__ = ["process_chat", "stream_agent"]
