# Generated by GitHub Copilot
"""Shared building blocks for the Wealth Management agents.

This module centralises everything the individual agent implementations have
in common so each agent module stays focused on its own logic:

    * ``get_shared_llm``   — a process-wide singleton LLM instance.
    * ``extract_text``     — normalise LLM response content (Gemini may return
                             a list of parts instead of a plain string).
    * ``BaseAgent``        — base class providing conversation-history helpers
                             (rolling summarisation + multi-turn formatting).

Each concrete agent (router, portfolio, relationship, general, clarification)
subclasses :class:`BaseAgent`.
"""
from __future__ import annotations

from typing import List, Optional, Union

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage

from app.services.llm import get_llm
from app.utils.logger import logger

# Maximum number of prior conversation turns (user+assistant pairs) to include.
MAX_HISTORY_TURNS = 6

# When history exceeds this many messages (user + assistant combined), the
# oldest turns are compressed into a rolling summary.  The 4 most-recent
# messages are always kept verbatim; earlier ones are summarised.
HISTORY_SUMMARY_THRESHOLD = 10

# Process-wide singleton so every agent shares one LLM client.
_shared_llm = None


def get_shared_llm():
    """Return a lazily-created, process-wide singleton LLM instance."""
    global _shared_llm
    if _shared_llm is None:
        _shared_llm = get_llm()
    return _shared_llm


def extract_text(content: Union[str, list, None]) -> str:
    """Normalise LLM response/chunk content to a plain string.

    Google Gemini may return content as a list of parts
    (e.g. ``[{"type": "text", "text": "..."}]``) instead of a plain ``str``.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, dict):
                parts.append(part.get("text", "") or part.get("content", ""))
            else:
                parts.append(str(part))
        return "".join(parts)
    if content is None:
        return ""
    return str(content)


class BaseAgent:
    """Base class for all agents — owns the shared LLM and history helpers."""

    def __init__(self):
        self.llm = get_shared_llm()

    # ─────────────────────────────────────────────────────────────────────
    # History helpers (shared by router + message builders)
    # ─────────────────────────────────────────────────────────────────────

    def _summarize_history(
        self,
        history: List[dict],
        existing_summary: Optional[str] = None,
    ) -> Optional[str]:
        """Summarise older conversation turns into a single rolling paragraph.

        The 4 most-recent messages are kept verbatim; everything older is
        compressed here.

        Args:
            history:          Full raw history list from ``memory_service``.
            existing_summary: Previously stored summary (if any) to build upon.

        Returns:
            A concise summary string, or ``None`` if summarisation fails.
        """
        to_summarise = history[:-4]  # keep last 4 verbatim
        if not to_summarise:
            return existing_summary
        turns_text = []
        for entry in to_summarise:
            role = "User" if entry.get("role") == "user" else "Assistant"
            turns_text.append(f"{role}: {entry.get('content', '')[:300]}")
        prior = (
            f"Existing summary:\n{existing_summary}\n\nAdditional turns:\n"
            if existing_summary
            else ""
        )
        prompt = (
            f"{prior}Summarise the following wealth-management conversation turns "
            "in 3-5 concise sentences, preserving key financial facts, client "
            "preferences, and decisions:\n\n" + "\n".join(turns_text)
        )
        try:
            result = self.llm.invoke([HumanMessage(content=prompt)])
            return extract_text(result.content).strip() or existing_summary
        except Exception:
            logger.warning("_summarize_history: LLM call failed (non-fatal); keeping old summary")
            return existing_summary

    def _format_history(
        self,
        history: List[dict],
        summary: Optional[str] = None,
        max_turns: int = MAX_HISTORY_TURNS,
    ) -> List[BaseMessage]:
        """Convert raw memory history dicts to LangChain multi-turn messages.

        When a *summary* is provided, the number of verbatim turns is reduced
        to 4 (the most recent), and the summary is prepended as a
        ``SystemMessage`` so older context is not lost.

        Args:
            history:   Raw session history from ``memory_service``.
            summary:   Rolling summary of turns older than the last 4.
            max_turns: Max (user+assistant) pairs to include verbatim when
                       no summary is present (default ``MAX_HISTORY_TURNS``).
        """
        if not history:
            return []
        recent_n = 4 if summary else max_turns * 2
        recent = history[-recent_n:]
        messages: List[BaseMessage] = []
        if summary:
            messages.append(
                SystemMessage(content=f"Summary of earlier conversation:\n{summary}")
            )
        for entry in recent:
            role = entry.get("role", "")
            content = str(entry.get("content", ""))
            if role == "user":
                messages.append(HumanMessage(content=content))
            elif role == "assistant":
                messages.append(AIMessage(content=content))
        return messages

    def _format_history_block(
        self, history: List[dict], max_turns: int = 3
    ) -> str:
        """Build a compact text block of recent conversation for the router prompt.

        Truncates long messages so the router input stays small.
        """
        if not history:
            return ""
        recent = history[-(max_turns * 2):]
        lines = ["Recent conversation:"]
        for entry in recent:
            role = "User" if entry.get("role") == "user" else "Helix"
            content = str(entry.get("content", "")).strip().replace("\n", " ")
            if len(content) > 200:
                content = content[:197] + "…"
            lines.append(f"  {role}: {content}")
        return "\n".join(lines) + "\n\n"
