# Generated by GitHub Copilot
"""Clarification agent.

Generates a single focused clarification question when the advisor's query is
genuinely ambiguous. Used by the streaming path only.
"""
from __future__ import annotations

from typing import List, Optional

from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage

from app.agents.base import BaseAgent
from app.agents.memory import long_term_memory
from app.prompts.clarification import (
    CLARIFICATION_SYSTEM_PROMPT,
    CLARIFICATION_USER_TEMPLATE,
)
from app.utils.logger import logger


class ClarificationAgent(BaseAgent):
    """Asks one targeted question to disambiguate an advisor's request."""

    def build_messages(
        self,
        user_msg: str,
        history: Optional[List[dict]] = None,
        client_id: Optional[str] = None,
        summary: Optional[str] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for generating a clarification question.

        Accepts an optional *client_id* so the clarifier can tailor its
        question using long-term knowledge of the client. When a *summary*
        is provided, older turns are compressed.
        """
        user_prompt = CLARIFICATION_USER_TEMPLATE.format(user_message=user_msg)
        history_messages = self._format_history(history or [], summary=summary)
        msgs: List[BaseMessage] = [SystemMessage(content=CLARIFICATION_SYSTEM_PROMPT)]
        # Inject long-term memory context if a client is identified
        if client_id and client_id not in {"", "unknown"}:
            try:
                lt_ctx = long_term_memory.format_long_term_context(client_id, user_msg)
                if lt_ctx:
                    msgs.append(SystemMessage(content=lt_ctx))
            except Exception:
                logger.warning("build_messages: long-term memory load failed (non-fatal)")
        msgs.extend(history_messages)
        msgs.append(HumanMessage(content=user_prompt))
        return msgs


# Module-level singleton shared across the orchestrator.
clarification_agent = ClarificationAgent()
