# Generated by GitHub Copilot
"""General / conversational agent.

Handles greetings, short follow-ups, and general wealth-management questions
that do not require live portfolio or CRM data. Used by the streaming path
only (the LangGraph route falls back to portfolio insights for this intent).
"""
from __future__ import annotations

from typing import List, Optional

from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage

from app.agents.base import BaseAgent
from app.agents.memory import long_term_memory
from app.prompts.general import GENERAL_SYSTEM_PROMPT, GENERAL_USER_TEMPLATE
from app.utils.logger import logger


class GeneralAgent(BaseAgent):
    """Conversational co-pilot for non-specialist exchanges."""

    def build_messages(
        self,
        user_msg: str,
        history: Optional[List[dict]] = None,
        client_id: Optional[str] = None,
        summary: Optional[str] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for direct conversational responses.

        Accepts an optional *client_id* so long-term memory context can be
        injected even for general (non-specialist-agent) intents. When a
        *summary* is provided, older turns are compressed.
        """
        user_prompt = GENERAL_USER_TEMPLATE.format(user_message=user_msg)
        history_messages = self._format_history(history or [], summary=summary)
        msgs: List[BaseMessage] = [SystemMessage(content=GENERAL_SYSTEM_PROMPT)]
        # Inject long-term memory context if a client is identified
        if client_id and client_id not in {"", "unknown"}:
            try:
                lt_ctx = long_term_memory.format_long_term_context(client_id, user_msg)
                if lt_ctx:
                    msgs.append(SystemMessage(content=lt_ctx))
            except Exception:
                logger.warning("build_messages: long-term memory load failed (non-fatal)")
        msgs.extend(history_messages)
        msgs.append(HumanMessage(content=user_prompt))
        return msgs


# Module-level singleton shared across the orchestrator.
general_agent = GeneralAgent()
