# Generated by GitHub Copilot
"""LangGraph orchestrator for the non-streaming REST path.

Wires the router and the two specialist agents into a graph. ``general`` and
``needs_clarification`` intents fall back to portfolio insights here, since the
graph path has no conversation history to act on (the streaming path in
``orchestrator.py`` handles all four intents fully).
"""
from langgraph.graph import StateGraph, END

from app.agents.state import AgentState
from app.agents.router import router_agent
from app.agents.portfolio_insights import portfolio_insights_agent
from app.agents.relationship_intelligence import relationship_intelligence_agent


def create_orchestrator():
    """Build and compile the LangGraph orchestrator for Wealth Management."""
    workflow = StateGraph(AgentState)

    # Nodes
    workflow.add_node("portfolio_insights", portfolio_insights_agent.run)
    workflow.add_node("relationship_intelligence", relationship_intelligence_agent.run)

    # Conditional entry — maps all 4 classifier outputs; general/clarification
    # route to portfolio_insights as the best-effort fallback for the REST path.
    workflow.set_conditional_entry_point(
        router_agent.router_node,
        {
            "portfolio_insights":        "portfolio_insights",
            "relationship_intelligence": "relationship_intelligence",
            "general":                   "portfolio_insights",
            "needs_clarification":       "portfolio_insights",
        },
    )

    workflow.add_edge("portfolio_insights", END)
    workflow.add_edge("relationship_intelligence", END)

    return workflow.compile()


app_graph = create_orchestrator()

