# Generated by GitHub Copilot
from __future__ import annotations

from typing import Literal, List, Union, Optional

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage

from app.agents.state import AgentState
from app.prompts.agent_prompts import (
    CLARIFICATION_SYSTEM_PROMPT,
    CLARIFICATION_USER_TEMPLATE,
    GENERAL_SYSTEM_PROMPT,
    GENERAL_USER_TEMPLATE,
    PORTFOLIO_INSIGHTS_SYSTEM_PROMPT,
    PORTFOLIO_INSIGHTS_USER_TEMPLATE,
    RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT,
    RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE,
    ROUTER_SYSTEM_PROMPT,
    ROUTER_USER_TEMPLATE,
)
from app.services.llm import get_llm
from app.utils.logger import logger

_GRAPH_AGENTS = {"portfolio_insights", "relationship_intelligence"}
_ALL_INTENTS = {"portfolio_insights", "relationship_intelligence", "general", "needs_clarification"}

# Maximum number of prior conversation turns (user+assistant pairs) to include.
_MAX_HISTORY_TURNS = 6


def _extract_text(content: Union[str, list, None]) -> str:
    """
    Normalise LLM response content.
    Google Gemini may return content as a list of parts instead of a plain str.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, dict):
                parts.append(part.get("text", "") or part.get("content", ""))
            else:
                parts.append(str(part))
        return "".join(parts)
    if content is None:
        return ""
    return str(content)


class AgentNodes:
    """LangGraph node implementations for the Wealth Management orchestrator."""

    def __init__(self):
        self.llm = get_llm()

    # ─────────────────────────────────────────────────────────────────────────
    # History helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _format_history(
        self, history: List[dict], max_turns: int = _MAX_HISTORY_TURNS
    ) -> List[BaseMessage]:
        """
        Convert raw memory history dicts to LangChain multi-turn messages.
        Limited to the most recent `max_turns` pairs to stay within token budgets.
        """
        if not history:
            return []
        recent = history[-(max_turns * 2):]
        messages: List[BaseMessage] = []
        for entry in recent:
            role = entry.get("role", "")
            content = str(entry.get("content", ""))
            if role == "user":
                messages.append(HumanMessage(content=content))
            elif role == "assistant":
                messages.append(AIMessage(content=content))
        return messages

    def _format_history_block(
        self, history: List[dict], max_turns: int = 3
    ) -> str:
        """
        Build a compact text block of recent conversation for the router prompt.
        Truncates long messages so the router input stays small.
        """
        if not history:
            return ""
        recent = history[-(max_turns * 2):]
        lines = ["Recent conversation:"]
        for entry in recent:
            role = "User" if entry.get("role") == "user" else "Helix"
            content = str(entry.get("content", "")).strip().replace("\n", " ")
            if len(content) > 200:
                content = content[:197] + "…"
            lines.append(f"  {role}: {content}")
        return "\n".join(lines) + "\n\n"

    # ─────────────────────────────────────────────────────────────────────────
    # LLM message builders
    # ─────────────────────────────────────────────────────────────────────────

    def _build_portfolio_messages(
        self,
        user_msg: str,
        session_id: str,
        client_id: str,
        history: Optional[List[dict]] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for the Portfolio Insights agent."""
        from app.services.tools import get_portfolio_summary, calculate_portfolio_metrics

        client_id = client_id or "unknown"
        try:
            portfolio_data = get_portfolio_summary.invoke({"client_id": client_id})
        except Exception as e:
            logger.warning(f"get_portfolio_summary failed for {client_id}: {e}")
            portfolio_data = {"error": str(e)}

        try:
            metrics_data = calculate_portfolio_metrics.invoke({"client_id": client_id})
        except Exception as e:
            logger.warning(f"calculate_portfolio_metrics failed for {client_id}: {e}")
            metrics_data = {"error": str(e)}

        context = (
            f"Client ID: {client_id}\n"
            f"Portfolio: {portfolio_data}\n"
            f"Metrics: {metrics_data}"
        )
        user_prompt = PORTFOLIO_INSIGHTS_USER_TEMPLATE.format(
            user_message=user_msg,
            additional_context=context,
        )
        history_messages = self._format_history(history or [])
        return [
            SystemMessage(content=PORTFOLIO_INSIGHTS_SYSTEM_PROMPT),
            *history_messages,
            HumanMessage(content=user_prompt),
        ]

    def _build_crm_messages(
        self,
        user_msg: str,
        session_id: str,
        client_id: str,
        history: Optional[List[dict]] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for the Relationship Intelligence agent."""
        from app.services.tools import get_client_engagement_history

        client_id = client_id or "unknown"
        try:
            crm_data = get_client_engagement_history.invoke({"client_id": client_id})
        except Exception as e:
            logger.warning(f"get_client_engagement_history failed for {client_id}: {e}")
            crm_data = {"error": str(e)}

        context = f"Client ID: {client_id}\nCRM Data: {crm_data}"
        user_prompt = RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE.format(
            user_message=user_msg,
            additional_context=context,
        )
        history_messages = self._format_history(history or [])
        return [
            SystemMessage(content=RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT),
            *history_messages,
            HumanMessage(content=user_prompt),
        ]

    def _build_general_messages(
        self,
        user_msg: str,
        history: Optional[List[dict]] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for direct conversational responses."""
        user_prompt = GENERAL_USER_TEMPLATE.format(user_message=user_msg)
        history_messages = self._format_history(history or [])
        return [
            SystemMessage(content=GENERAL_SYSTEM_PROMPT),
            *history_messages,
            HumanMessage(content=user_prompt),
        ]

    def _build_clarification_messages(
        self,
        user_msg: str,
        history: Optional[List[dict]] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for generating a clarification question."""
        user_prompt = CLARIFICATION_USER_TEMPLATE.format(user_message=user_msg)
        history_messages = self._format_history(history or [])
        return [
            SystemMessage(content=CLARIFICATION_SYSTEM_PROMPT),
            *history_messages,
            HumanMessage(content=user_prompt),
        ]

    # ─────────────────────────────────────────────────────────────────────────
    # Intent classifiers
    # ─────────────────────────────────────────────────────────────────────────

    async def classify_intent(
        self,
        user_msg: str,
        history: Optional[List[dict]] = None,
    ) -> Literal["portfolio_insights", "relationship_intelligence", "general", "needs_clarification"]:
        """
        Full 4-way intent classifier for the streaming path.
        Uses conversation history for context-aware routing.
        Returns one of: portfolio_insights | relationship_intelligence | general | needs_clarification
        """
        logger.info("classify_intent: classifying user intent")

        if not user_msg.strip():
            return "general"

        history_block = self._format_history_block(history or [])
        classification_messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=ROUTER_USER_TEMPLATE.format(
                history_block=history_block,
                user_message=user_msg,
            )),
        ]

        try:
            result = await self.llm.ainvoke(classification_messages)
            raw = _extract_text(result.content).strip().lower().rstrip(".")
            candidate = raw.split()[0] if raw.split() else ""

            if candidate in _ALL_INTENTS:
                logger.info(f"classify_intent → {candidate}")
                return candidate

            # Fuzzy fallbacks
            if "relationship" in raw or "crm" in raw or "intelligence" in raw:
                return "relationship_intelligence"
            if "portfolio" in raw or "invest" in raw:
                return "portfolio_insights"
            if "clarif" in raw:
                return "needs_clarification"

            logger.warning(f"classify_intent: unrecognised '{raw}', defaulting to general")
            return "general"

        except Exception as e:
            logger.error(f"classify_intent error: {e}", exc_info=True)
            return "portfolio_insights"

    async def router_node(
        self, state: AgentState
    ) -> Literal["portfolio_insights", "relationship_intelligence", "general", "needs_clarification"]:
        """
        LangGraph conditional entry-point router (2-way, no history).
        Used by the non-streaming graph path (process_chat / REST endpoint).
        Falls back to portfolio_insights on error or unrecognised output.
        """
        logger.info("Running LLM Router Node")

        messages = state.get("messages") or []
        if not messages:
            logger.warning("Router: empty messages list, defaulting to portfolio_insights")
            return "portfolio_insights"

        user_msg = _extract_text(messages[-1].content)
        if not user_msg.strip():
            return "portfolio_insights"

        history_block = ""  # No history available in graph path
        classification_messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=ROUTER_USER_TEMPLATE.format(
                history_block=history_block,
                user_message=user_msg,
            )),
        ]

        try:
            result = await self.llm.ainvoke(classification_messages)
            raw = _extract_text(result.content).strip().lower().rstrip(".")
            candidate = raw.split()[0] if raw.split() else ""

            if candidate in _ALL_INTENTS:
                logger.info(f"LLM router → {candidate}")
                return candidate

            if "relationship" in raw or "crm" in raw or "intelligence" in raw:
                return "relationship_intelligence"

            logger.warning(f"Router: unrecognised '{raw}', defaulting to portfolio_insights")
            return "portfolio_insights"

        except Exception as e:
            logger.error(f"LLM router error: {e}", exc_info=True)
            return "portfolio_insights"

    # ─────────────────────────────────────────────────────────────────────────
    # Agent nodes (non-streaming LangGraph path)
    # ─────────────────────────────────────────────────────────────────────────

    async def portfolio_insights_agent(self, state: AgentState) -> AgentState:
        """Fetch portfolio data, invoke the LLM, and return the response."""
        logger.info("Running Portfolio Insights Agent")
        try:
            messages = state.get("messages") or []
            user_msg = _extract_text(messages[-1].content) if messages else ""
            client_id = state.get("metadata", {}).get("client_id") or "unknown"

            llm_messages = self._build_portfolio_messages(
                user_msg, state.get("session_id", ""), client_id
            )
            result = await self.llm.ainvoke(llm_messages)
            response = _extract_text(result.content)
            if not response:
                response = "I was unable to generate a portfolio analysis. Please try again."
            return {
                "messages": [AIMessage(content=response)],
                "final_output": response,
                "next_agent": "portfolio_insights",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }
        except Exception as e:
            logger.error(f"Error in portfolio_insights_agent: {e}", exc_info=True)
            error_msg = f"I encountered an error analyzing your portfolio: {str(e)}"
            return {
                "messages": [AIMessage(content=error_msg)],
                "final_output": error_msg,
                "next_agent": "portfolio_insights",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }

    async def relationship_intelligence_agent(self, state: AgentState) -> AgentState:
        """Fetch CRM data, invoke the LLM, and return the response."""
        logger.info("Running Relationship Intelligence Agent")
        try:
            messages = state.get("messages") or []
            user_msg = _extract_text(messages[-1].content) if messages else ""
            client_id = state.get("metadata", {}).get("client_id") or "unknown"

            llm_messages = self._build_crm_messages(
                user_msg, state.get("session_id", ""), client_id
            )
            result = await self.llm.ainvoke(llm_messages)
            response = _extract_text(result.content)
            if not response:
                response = "I was unable to generate a relationship analysis. Please try again."
            return {
                "messages": [AIMessage(content=response)],
                "final_output": response,
                "next_agent": "relationship_intelligence",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }
        except Exception as e:
            logger.error(f"Error in relationship_intelligence_agent: {e}", exc_info=True)
            error_msg = f"I encountered an error analyzing client relationships: {str(e)}"
            return {
                "messages": [AIMessage(content=error_msg)],
                "final_output": error_msg,
                "next_agent": "relationship_intelligence",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }


nodes = AgentNodes()
