# Generated by GitHub Copilot
from __future__ import annotations

from typing import AsyncGenerator

from langchain_core.messages import HumanMessage

from app.agents.base import extract_text as _extract_text, get_shared_llm
from app.agents.graph import app_graph
from app.agents.memory import long_term_memory
from app.utils.logger import logger


async def process_chat(message: str, session_id: str, metadata: dict = None) -> dict:
    """
    Non-streaming path: run the full LangGraph pipeline and return the result dict.
    Used by the /chat REST endpoint.
    """
    logger.info(f"process_chat: session={session_id}")

    initial_state = {
        "messages": [HumanMessage(content=message)],
        "session_id": session_id,
        "metadata": metadata or {},
        "next_agent": "",
        "final_output": "",
    }

    try:
        result = await app_graph.ainvoke(
            initial_state, config={"configurable": {"thread_id": session_id}}
        )
        logger.info(f"process_chat complete: session={session_id}")
        return result
    except Exception as e:
        logger.error(f"process_chat error: {e}", exc_info=True)
        raise


async def stream_agent(
    message: str, session_id: str, metadata: dict = None
) -> AsyncGenerator[dict, None]:
    """
    Streaming path: yields SSE-style dicts as the pipeline progresses.

    Event shapes:
      {"type": "step",  "node": str, "state": "running" | "done"}
      {"type": "token", "content": str}
      {"type": "done",  "agent_used": str, "full_response": str}
      {"type": "error", "message": str}

    Intent routing (4-way):
      general                  → direct LLM with conversation history, no tool data
      portfolio_insights       → Portfolio Insights agent with live portfolio/metrics data
      relationship_intelligence→ Relationship Intelligence agent with live CRM data
      needs_clarification      → LLM generates a focused clarification question

    Conversation history is loaded from memory and injected into every LLM call
    so the model maintains context across turns.
    """
    from app.agents.router import router_agent
    from app.agents.portfolio_insights import portfolio_insights_agent
    from app.agents.relationship_intelligence import relationship_intelligence_agent
    from app.agents.general import general_agent
    from app.agents.clarification import clarification_agent
    from app.services.memory import memory_service

    client_id = (metadata or {}).get("client_id") or "unknown"

    if not message or not message.strip():
        yield {"type": "error", "message": "Message cannot be empty."}
        return

    # ── Load conversation history (exclude the current user message just saved) ──
    raw_history = memory_service.get_history(session_id or "")
    # The current user message was persisted before this call; strip it so agents
    # only see prior turns as history context.
    if raw_history and raw_history[-1].get("role") == "user":
        prior_history = raw_history[:-1]
    else:
        prior_history = raw_history

    # ── Load existing short-term memory summary (if any) ────────────────────
    existing_summary = memory_service.get_summary(session_id or "")

    # ── 1. Intent classification (4-way, context-aware) ───────────────────────
    yield {"type": "step", "node": "router", "state": "running"}

    try:
        intent, updated_summary = await router_agent.classify_intent(
            message, history=prior_history, existing_summary=existing_summary
        )
    except Exception as e:
        logger.error(f"classify_intent error: {e}", exc_info=True)
        yield {"type": "error", "message": "Router failed. Please try again."}
        return

    # Persist updated summary back to session store if it changed
    if updated_summary and updated_summary != existing_summary:
        try:
            memory_service.save_summary(session_id or "", updated_summary)
        except Exception:
            logger.warning("stream_agent: failed to persist summary (non-fatal)")

    yield {"type": "step", "node": "router", "state": "done"}
    logger.info(f"stream_agent: intent={intent} session={session_id}")

    # ── 2. Build LLM messages for the resolved intent ─────────────────────────
    yield {"type": "step", "node": intent, "state": "running"}

    try:
        if intent == "portfolio_insights":
            llm_messages = portfolio_insights_agent.build_messages(
                message, session_id or "", client_id,
                history=prior_history, summary=updated_summary
            )
        elif intent == "relationship_intelligence":
            llm_messages = relationship_intelligence_agent.build_messages(
                message, session_id or "", client_id,
                history=prior_history, summary=updated_summary
            )
        elif intent == "general":
            llm_messages = general_agent.build_messages(
                message, history=prior_history,
                client_id=client_id, summary=updated_summary
            )
        else:  # needs_clarification
            llm_messages = clarification_agent.build_messages(
                message, history=prior_history,
                client_id=client_id, summary=updated_summary
            )
    except Exception as e:
        logger.error(f"Message build error: {e}", exc_info=True)
        yield {"type": "error", "message": f"Failed to prepare response: {str(e)}"}
        return

    # ── 3. Stream LLM tokens ──────────────────────────────────────────────────
    full_response = ""
    try:
        async for chunk in get_shared_llm().astream(llm_messages):
            token = _extract_text(chunk.content)
            if token:
                full_response += token
                yield {"type": "token", "content": token}
    except Exception as e:
        logger.error(f"LLM stream error: {e}", exc_info=True)
        if full_response:
            # Deliver whatever arrived before the error
            yield {"type": "done", "agent_used": intent, "full_response": full_response}
        else:
            yield {"type": "error", "message": f"LLM error: {str(e)}"}
        return

    if not full_response:
        yield {"type": "error", "message": "The model returned an empty response. Please try again."}
        return

    yield {"type": "step", "node": intent, "state": "done"}
    yield {"type": "done", "agent_used": intent, "full_response": full_response}

    # ── 4. Persist long-term memory (non-blocking, fail-silent) ───────────────
    # Runs *after* yielding "done" so it never delays the streamed response.
    try:
        long_term_memory.save_turn_facts(
            client_id=client_id,
            session_id=session_id or "",
            query=message,
            answer=full_response,
            intent=intent,
        )
    except Exception:
        logger.warning("stream_agent: long-term memory save failed (non-fatal)")
