# Generated by GitHub Copilot
from __future__ import annotations

from typing import AsyncGenerator, Union

from langchain_core.messages import HumanMessage

from app.agents.graph import app_graph
from app.utils.logger import logger


def _extract_text(content: Union[str, list, None]) -> str:
    """
    Normalise LLM chunk/response content.

    Google Gemini may return content as a list of parts
    (e.g. [{"type": "text", "text": "..."}]) instead of a plain str.
    This helper always returns a str.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, dict):
                parts.append(part.get("text", "") or part.get("content", ""))
            else:
                parts.append(str(part))
        return "".join(parts)
    if content is None:
        return ""
    return str(content)


async def process_chat(message: str, session_id: str, metadata: dict = None) -> dict:
    """
    Non-streaming path: run the full LangGraph pipeline and return the result dict.
    Used by the /chat REST endpoint.
    """
    logger.info(f"process_chat: session={session_id}")

    initial_state = {
        "messages": [HumanMessage(content=message)],
        "session_id": session_id,
        "metadata": metadata or {},
        "next_agent": "",
        "final_output": "",
    }

    try:
        result = await app_graph.ainvoke(
            initial_state, config={"configurable": {"thread_id": session_id}}
        )
        logger.info(f"process_chat complete: session={session_id}")
        return result
    except Exception as e:
        logger.error(f"process_chat error: {e}", exc_info=True)
        raise


async def stream_agent(
    message: str, session_id: str, metadata: dict = None
) -> AsyncGenerator[dict, None]:
    """
    Streaming path: yields SSE-style dicts as the pipeline progresses.

    Event shapes:
      {"type": "step",  "node": str, "state": "running" | "done"}
      {"type": "token", "content": str}
      {"type": "done",  "agent_used": str, "full_response": str}
      {"type": "error", "message": str}

    Intent routing (4-way):
      general                  → direct LLM with conversation history, no tool data
      portfolio_insights       → Portfolio Insights agent with live portfolio/metrics data
      relationship_intelligence→ Relationship Intelligence agent with live CRM data
      needs_clarification      → LLM generates a focused clarification question

    Conversation history is loaded from memory and injected into every LLM call
    so the model maintains context across turns.
    """
    from app.agents.nodes import nodes
    from app.services.memory import memory_service

    client_id = (metadata or {}).get("client_id") or "unknown"

    if not message or not message.strip():
        yield {"type": "error", "message": "Message cannot be empty."}
        return

    # ── Load conversation history (exclude the current user message just saved) ──
    raw_history = memory_service.get_history(session_id or "")
    # The current user message was persisted before this call; strip it so agents
    # only see prior turns as history context.
    if raw_history and raw_history[-1].get("role") == "user":
        prior_history = raw_history[:-1]
    else:
        prior_history = raw_history

    # ── 1. Intent classification (4-way, context-aware) ───────────────────────
    yield {"type": "step", "node": "router", "state": "running"}

    try:
        intent = await nodes.classify_intent(message, history=prior_history)
    except Exception as e:
        logger.error(f"classify_intent error: {e}", exc_info=True)
        yield {"type": "error", "message": "Router failed. Please try again."}
        return

    yield {"type": "step", "node": "router", "state": "done"}
    logger.info(f"stream_agent: intent={intent} session={session_id}")

    # ── 2. Build LLM messages for the resolved intent ─────────────────────────
    yield {"type": "step", "node": intent, "state": "running"}

    try:
        if intent == "portfolio_insights":
            llm_messages = nodes._build_portfolio_messages(
                message, session_id or "", client_id, history=prior_history
            )
        elif intent == "relationship_intelligence":
            llm_messages = nodes._build_crm_messages(
                message, session_id or "", client_id, history=prior_history
            )
        elif intent == "general":
            llm_messages = nodes._build_general_messages(
                message, history=prior_history
            )
        else:  # needs_clarification
            llm_messages = nodes._build_clarification_messages(
                message, history=prior_history
            )
    except Exception as e:
        logger.error(f"Message build error: {e}", exc_info=True)
        yield {"type": "error", "message": f"Failed to prepare response: {str(e)}"}
        return

    # ── 3. Stream LLM tokens ──────────────────────────────────────────────────
    full_response = ""
    try:
        async for chunk in nodes.llm.astream(llm_messages):
            token = _extract_text(chunk.content)
            if token:
                full_response += token
                yield {"type": "token", "content": token}
    except Exception as e:
        logger.error(f"LLM stream error: {e}", exc_info=True)
        if full_response:
            # Deliver whatever arrived before the error
            yield {"type": "done", "agent_used": intent, "full_response": full_response}
        else:
            yield {"type": "error", "message": f"LLM error: {str(e)}"}
        return

    if not full_response:
        yield {"type": "error", "message": "The model returned an empty response. Please try again."}
        return

    yield {"type": "step", "node": intent, "state": "done"}
    yield {"type": "done", "agent_used": intent, "full_response": full_response}
