# Generated by GitHub Copilot
from __future__ import annotations

import asyncio
from typing import AsyncGenerator

from langchain_core.messages import HumanMessage

from app.agents.base import extract_text as _extract_text
from app.agents.graph import app_graph
from app.agents.memory import long_term_memory
from app.utils.logger import logger


async def process_chat(message: str, session_id: str, metadata: dict = None) -> dict:
    """Non-streaming REST path — run full LangGraph pipeline and return result."""
    logger.info(f"process_chat: session={session_id}")
    initial_state = {
        "messages": [HumanMessage(content=message)],
        "session_id": session_id,
        "metadata": metadata or {},
        "route": "",
        "portfolio_output": {},
        "crm_output": {},
        "final_output": "",
        "citations": [],
        "is_sufficient": True,
        "clarification_needed": "",
        "retry_count": 0,
        "next_agent": "",
    }
    try:
        result = await app_graph.ainvoke(
            initial_state, config={"configurable": {"thread_id": session_id}}
        )
        logger.info(f"process_chat complete: session={session_id}")
        return result
    except Exception as e:
        logger.error(f"process_chat error: {e}", exc_info=True)
        raise


async def stream_agent(
    message: str, session_id: str, metadata: dict = None
) -> AsyncGenerator[dict, None]:
    """Streaming path — yields SSE-style dicts as the pipeline progresses.

    Flow:
      1. LLM intent classification → route.
      2. Run portfolio and/or CRM agents in parallel (silent, no streaming).
      3. Stream synthesizer response token-by-token.
      4. If data was insufficient → stream clarification question instead.

    Event shapes:
      {"type": "step",  "node": str, "state": "running"|"done"}
      {"type": "token", "content": str}
      {"type": "done",  "agent_used": str, "full_response": str}
      {"type": "error", "message": str}
    """
    from app.agents.router import router_agent
    from app.agents.portfolio_insights import portfolio_insights_agent
    from app.agents.relationship_intelligence import relationship_intelligence_agent
    from app.agents.synthesizer import synthesizer_agent
    from app.services.memory import memory_service

    client_id = (metadata or {}).get("client_id") or "unknown"
    state_base: dict = {
        "messages": [HumanMessage(content=message)],
        "session_id": session_id or "",
        "metadata": metadata or {},
        "route": "",
        "portfolio_output": {},
        "crm_output": {},
        "final_output": "",
        "citations": [],
        "is_sufficient": True,
        "clarification_needed": "",
        "retry_count": 0,
        "next_agent": "",
    }

    if not message or not message.strip():
        yield {"type": "error", "message": "Message cannot be empty."}
        return


    # ── Load memory ───────────────────────────────────────────────────────────
    raw_history = memory_service.get_history(session_id or "")
    prior_history = raw_history[:-1] if (raw_history and raw_history[-1].get("role") == "user") else raw_history
    existing_summary = memory_service.get_summary(session_id or "")

    # ── 2. Intent classification ──────────────────────────────────────────────
    yield {"type": "step", "node": "router", "state": "running"}
    yield {"type": "activity", "icon": "route", "msg": "Router: classifying query..."}
    try:
        route, updated_summary = await router_agent.classify_intent(
            message, history=prior_history, existing_summary=existing_summary
        )
    except Exception as e:
        logger.error(f"classify_intent error: {e}", exc_info=True)
        yield {"type": "error", "message": "Router failed. Please try again."}
        return

    if updated_summary and updated_summary != existing_summary:
        try:
            memory_service.save_summary(session_id or "", updated_summary)
        except Exception:
            pass

    yield {"type": "step", "node": "router", "state": "done"}
    yield {"type": "activity", "icon": "route", "msg": f"Router: intent = {route}", "done": True}
    state_base["route"] = route
    logger.info(f"stream_agent: route={route} session={session_id}")

    # ── 3. General route — synthesizer with no tool data ─────────────────────
    if route == "general":
        yield {"type": "step", "node": "synthesizer", "state": "running"}
        yield {"type": "activity", "icon": "write", "msg": "Synthesizer: generating response..."}
        full_response = ""
        async for token in synthesizer_agent.stream_run(state_base, prior_history, updated_summary):
            full_response += token
            yield {"type": "token", "content": token}
        yield {"type": "step", "node": "synthesizer", "state": "done"}
        yield {"type": "activity", "icon": "check", "msg": "Done", "done": True}
        yield {"type": "done", "agent_used": "general", "full_response": full_response}
        _save_long_term(client_id, session_id, message, full_response, route)
        return

    # ── 4. Run agents (parallel for 'both') ──────────────────────────────────
    if route in ("portfolio_only", "both"):
        yield {"type": "step", "node": "portfolio_agent", "state": "running"}
        yield {"type": "activity", "icon": "agent", "msg": "Portfolio Agent: fetching data..."}
    if route in ("crm_only", "both"):
        yield {"type": "step", "node": "crm_agent", "state": "running"}
        yield {"type": "activity", "icon": "agent", "msg": "CRM Agent: fetching interaction data..."}

    try:
        if route == "portfolio_only":
            portfolio_data = await portfolio_insights_agent.collect_data(
                state_base, history=prior_history, summary=updated_summary
            )
            state_base["portfolio_output"] = portfolio_data

        elif route == "crm_only":
            crm_data = await relationship_intelligence_agent.collect_data(
                state_base, history=prior_history, summary=updated_summary
            )
            state_base["crm_output"] = crm_data

        else:  # both — parallel
            portfolio_task = portfolio_insights_agent.collect_data(
                state_base, history=prior_history, summary=updated_summary
            )
            crm_task = relationship_intelligence_agent.collect_data(
                state_base, history=prior_history, summary=updated_summary
            )
            portfolio_data, crm_data = await asyncio.gather(portfolio_task, crm_task)
            state_base["portfolio_output"] = portfolio_data
            state_base["crm_output"] = crm_data

    except Exception as e:
        logger.error(f"Agent data collection error: {e}", exc_info=True)
        yield {"type": "error", "message": f"Failed to retrieve data: {str(e)}"}
        return

    if route in ("portfolio_only", "both"):
        tools_p = (state_base.get("portfolio_output") or {}).get("tools_called", [])
        yield {"type": "step", "node": "portfolio_agent", "state": "done"}
        yield {"type": "activity", "icon": "tool", "msg": f"Portfolio: {', '.join(tools_p) or 'no tools called'}", "done": True}
    if route in ("crm_only", "both"):
        tools_c = (state_base.get("crm_output") or {}).get("tools_called", [])
        yield {"type": "step", "node": "crm_agent", "state": "done"}
        yield {"type": "activity", "icon": "tool", "msg": f"CRM: {', '.join(tools_c) or 'no tools called'}", "done": True}

    # ── 5. Synthesize and stream response ─────────────────────────────────────
    yield {"type": "step", "node": "synthesizer", "state": "running"}
    yield {"type": "activity", "icon": "write", "msg": "Synthesizer: generating response..."}
    full_response = ""
    try:
        async for token in synthesizer_agent.stream_run(state_base, prior_history, updated_summary):
            full_response += token
            yield {"type": "token", "content": token}
    except Exception as e:
        logger.error(f"Synthesizer stream error: {e}", exc_info=True)
        if full_response:
            yield {"type": "done", "agent_used": route, "full_response": full_response}
        else:
            yield {"type": "error", "message": f"Synthesis error: {str(e)}"}
        return

    if not full_response:
        yield {"type": "error", "message": "The model returned an empty response."}
        return

    yield {"type": "step", "node": "synthesizer", "state": "done"}
    yield {"type": "activity", "icon": "check", "msg": "Done", "done": True}
    yield {"type": "done", "agent_used": route, "full_response": full_response}

    # LTM_DISABLED — uncomment when embeddings are available on this machine
    # _save_long_term(client_id, session_id, message, full_response, route)


def _save_long_term(client_id: str, session_id: str, query: str, answer: str, intent: str) -> None:
    """Persist turn facts to long-term memory (non-blocking, fail-silent)."""
    try:
        long_term_memory.save_turn_facts(
            client_id=client_id,
            session_id=session_id or "",
            query=query,
            answer=answer,
            intent=intent,
        )
    except Exception:
        logger.warning("stream_agent: long-term memory save failed (non-fatal)")


