# Generated by GitHub Copilot
"""Portfolio Insights agent.

Produces data-backed portfolio analysis. Fetches live portfolio + metrics via
tools, grounds the response in long-term client memory, and runs the LLM. The
streaming path calls :meth:`build_messages`; the LangGraph path calls
:meth:`run`.
"""
from __future__ import annotations

from typing import List, Optional

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage

from app.agents.base import BaseAgent, extract_text
from app.agents.memory import long_term_memory
from app.agents.state import AgentState
from app.prompts.portfolio_insights import (
    PORTFOLIO_INSIGHTS_SYSTEM_PROMPT,
    PORTFOLIO_INSIGHTS_USER_TEMPLATE,
)
from app.utils.logger import logger


class PortfolioInsightsAgent(BaseAgent):
    """Senior wealth-analyst agent for portfolio analysis."""

    def build_messages(
        self,
        user_msg: str,
        session_id: str,
        client_id: str,
        history: Optional[List[dict]] = None,
        summary: Optional[str] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for the Portfolio Insights agent.

        Prepends a long-term memory SystemMessage (preferences + episodic +
        semantic + procedural) so the agent is grounded in durable client
        knowledge. When a *summary* is provided, older history turns are
        replaced by the summary SystemMessage and only the last 4 turns are
        sent verbatim.
        """
        from app.services.tools import get_portfolio_summary, calculate_portfolio_metrics

        client_id = client_id or "unknown"
        try:
            portfolio_data = get_portfolio_summary.invoke({"client_id": client_id})
        except Exception as e:
            logger.warning(f"get_portfolio_summary failed for {client_id}: {e}")
            portfolio_data = {"error": str(e)}

        try:
            metrics_data = calculate_portfolio_metrics.invoke({"client_id": client_id})
        except Exception as e:
            logger.warning(f"calculate_portfolio_metrics failed for {client_id}: {e}")
            metrics_data = {"error": str(e)}

        context = (
            f"Client ID: {client_id}\n"
            f"Portfolio: {portfolio_data}\n"
            f"Metrics: {metrics_data}"
        )
        user_prompt = PORTFOLIO_INSIGHTS_USER_TEMPLATE.format(
            user_message=user_msg,
            additional_context=context,
        )
        history_messages = self._format_history(history or [], summary=summary)
        msgs: List[BaseMessage] = [SystemMessage(content=PORTFOLIO_INSIGHTS_SYSTEM_PROMPT)]
        # Inject long-term memory context if available
        try:
            lt_ctx = long_term_memory.format_long_term_context(client_id, user_msg)
            if lt_ctx:
                msgs.append(SystemMessage(content=lt_ctx))
        except Exception:
            logger.warning("build_messages: long-term memory load failed (non-fatal)")
        msgs.extend(history_messages)
        msgs.append(HumanMessage(content=user_prompt))
        return msgs

    async def run(self, state: AgentState) -> AgentState:
        """LangGraph node: fetch portfolio data, invoke the LLM, return the response."""
        logger.info("Running Portfolio Insights Agent")
        try:
            messages = state.get("messages") or []
            user_msg = extract_text(messages[-1].content) if messages else ""
            client_id = state.get("metadata", {}).get("client_id") or "unknown"

            llm_messages = self.build_messages(
                user_msg, state.get("session_id", ""), client_id
            )
            result = await self.llm.ainvoke(llm_messages)
            response = extract_text(result.content)
            if not response:
                response = "I was unable to generate a portfolio analysis. Please try again."
            return {
                "messages": [AIMessage(content=response)],
                "final_output": response,
                "next_agent": "portfolio_insights",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }
        except Exception as e:
            logger.error(f"Error in PortfolioInsightsAgent.run: {e}", exc_info=True)
            error_msg = f"I encountered an error analyzing your portfolio: {str(e)}"
            return {
                "messages": [AIMessage(content=error_msg)],
                "final_output": error_msg,
                "next_agent": "portfolio_insights",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }


# Module-level singleton shared across the orchestrator and graph.
portfolio_insights_agent = PortfolioInsightsAgent()
