# Generated by GitHub Copilot
"""Relationship Intelligence agent.

Synthesises CRM engagement data into relationship-health assessments and
proactive engagement strategies. The streaming path calls
:meth:`build_messages`; the LangGraph path calls :meth:`run`.
"""
from __future__ import annotations

from typing import List, Optional

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage

from app.agents.base import BaseAgent, extract_text
from app.agents.memory import long_term_memory
from app.agents.state import AgentState
from app.prompts.relationship_intelligence import (
    RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT,
    RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE,
)
from app.utils.logger import logger


class RelationshipIntelligenceAgent(BaseAgent):
    """Expert CRM-advisor agent for client-relationship intelligence."""

    def build_messages(
        self,
        user_msg: str,
        session_id: str,
        client_id: str,
        history: Optional[List[dict]] = None,
        summary: Optional[str] = None,
    ) -> List[BaseMessage]:
        """Return the LLM message list for the Relationship Intelligence agent.

        Prepends a long-term memory SystemMessage so the agent is grounded in
        durable client-relationship knowledge across sessions. When a *summary*
        is provided, older history turns are replaced by the summary
        SystemMessage and only the last 4 turns are sent verbatim.
        """
        from app.services.tools import get_client_engagement_history

        client_id = client_id or "unknown"
        try:
            crm_data = get_client_engagement_history.invoke({"client_id": client_id})
        except Exception as e:
            logger.warning(f"get_client_engagement_history failed for {client_id}: {e}")
            crm_data = {"error": str(e)}

        context = f"Client ID: {client_id}\nCRM Data: {crm_data}"
        user_prompt = RELATIONSHIP_INTELLIGENCE_USER_TEMPLATE.format(
            user_message=user_msg,
            additional_context=context,
        )
        history_messages = self._format_history(history or [], summary=summary)
        msgs: List[BaseMessage] = [
            SystemMessage(content=RELATIONSHIP_INTELLIGENCE_SYSTEM_PROMPT)
        ]
        # Inject long-term memory context if available
        try:
            lt_ctx = long_term_memory.format_long_term_context(client_id, user_msg)
            if lt_ctx:
                msgs.append(SystemMessage(content=lt_ctx))
        except Exception:
            logger.warning("build_messages: long-term memory load failed (non-fatal)")
        msgs.extend(history_messages)
        msgs.append(HumanMessage(content=user_prompt))
        return msgs

    async def run(self, state: AgentState) -> AgentState:
        """LangGraph node: fetch CRM data, invoke the LLM, return the response."""
        logger.info("Running Relationship Intelligence Agent")
        try:
            messages = state.get("messages") or []
            user_msg = extract_text(messages[-1].content) if messages else ""
            client_id = state.get("metadata", {}).get("client_id") or "unknown"

            llm_messages = self.build_messages(
                user_msg, state.get("session_id", ""), client_id
            )
            result = await self.llm.ainvoke(llm_messages)
            response = extract_text(result.content)
            if not response:
                response = "I was unable to generate a relationship analysis. Please try again."
            return {
                "messages": [AIMessage(content=response)],
                "final_output": response,
                "next_agent": "relationship_intelligence",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }
        except Exception as e:
            logger.error(f"Error in RelationshipIntelligenceAgent.run: {e}", exc_info=True)
            error_msg = f"I encountered an error analyzing client relationships: {str(e)}"
            return {
                "messages": [AIMessage(content=error_msg)],
                "final_output": error_msg,
                "next_agent": "relationship_intelligence",
                "session_id": state.get("session_id", ""),
                "metadata": state.get("metadata", {}),
            }


# Module-level singleton shared across the orchestrator and graph.
relationship_intelligence_agent = RelationshipIntelligenceAgent()
