# Generated by GitHub Copilot
"""Router / intent-classification agent.

Decides which specialist handles an advisor's message. Two entry points:

    * :meth:`RouterAgent.classify_intent` — full 4-way, history-aware classifier
      used by the streaming path (``orchestrator.stream_agent``). It also rolls
      up short-term memory into a summary once history grows long.
    * :meth:`RouterAgent.router_node`     — LangGraph conditional entry point
      used by the non-streaming REST graph (``app.agents.graph``).
"""
from __future__ import annotations

from typing import Literal, Optional

from langchain_core.messages import HumanMessage, SystemMessage

from app.agents.base import BaseAgent, HISTORY_SUMMARY_THRESHOLD, extract_text
from app.agents.state import AgentState
from app.prompts.router import ROUTER_SYSTEM_PROMPT, ROUTER_USER_TEMPLATE
from app.utils.logger import logger

# All intents the classifier may emit.
INTENTS = {
    "portfolio_insights",
    "relationship_intelligence",
    "general",
    "needs_clarification",
}


class RouterAgent(BaseAgent):
    """LLM-based intent classifier for the orchestrator."""

    async def classify_intent(
        self,
        user_msg: str,
        history: Optional[list] = None,
        existing_summary: Optional[str] = None,
    ) -> tuple:
        """Full 4-way intent classifier for the streaming path.

        Also computes a rolling short-term memory summary when the session
        history has grown beyond ``HISTORY_SUMMARY_THRESHOLD`` messages.

        Args:
            user_msg:         Current user message.
            history:          Full raw session history from ``memory_service``.
            existing_summary: Previously stored summary for this session.

        Returns:
            A 2-tuple ``(intent, summary)`` where *intent* is one of
            ``portfolio_insights | relationship_intelligence | general |
            needs_clarification`` and *summary* is either the updated rolling
            summary string or ``None`` if the threshold has not been reached.
        """
        logger.info("classify_intent: classifying user intent")

        if not user_msg.strip():
            return "general", existing_summary

        # ── Short-term memory: compress history when it grows too long ─────
        summary = existing_summary
        if len(history or []) > HISTORY_SUMMARY_THRESHOLD:
            summary = self._summarize_history(history, existing_summary)

        history_block = self._format_history_block(history or [])
        classification_messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=ROUTER_USER_TEMPLATE.format(
                history_block=history_block,
                user_message=user_msg,
            )),
        ]

        try:
            result = await self.llm.ainvoke(classification_messages)
            raw = extract_text(result.content).strip().lower().rstrip(".")
            candidate = raw.split()[0] if raw.split() else ""

            if candidate in INTENTS:
                logger.info(f"classify_intent → {candidate}")
                return candidate, summary

            # Fuzzy fallbacks
            if "relationship" in raw or "crm" in raw or "intelligence" in raw:
                return "relationship_intelligence", summary
            if "portfolio" in raw or "invest" in raw:
                return "portfolio_insights", summary
            if "clarif" in raw:
                return "needs_clarification", summary

            logger.warning(f"classify_intent: unrecognised '{raw}', defaulting to general")
            return "general", summary

        except Exception as e:
            logger.error(f"classify_intent error: {e}", exc_info=True)
            return "portfolio_insights", summary

    async def router_node(
        self, state: AgentState
    ) -> Literal[
        "portfolio_insights",
        "relationship_intelligence",
        "general",
        "needs_clarification",
    ]:
        """LangGraph conditional entry-point router (no history).

        Used by the non-streaming graph path (process_chat / REST endpoint).
        Falls back to portfolio_insights on error or unrecognised output.
        """
        logger.info("Running LLM Router Node")

        messages = state.get("messages") or []
        if not messages:
            logger.warning("Router: empty messages list, defaulting to portfolio_insights")
            return "portfolio_insights"

        user_msg = extract_text(messages[-1].content)
        if not user_msg.strip():
            return "portfolio_insights"

        history_block = ""  # No history available in graph path
        classification_messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=ROUTER_USER_TEMPLATE.format(
                history_block=history_block,
                user_message=user_msg,
            )),
        ]

        try:
            result = await self.llm.ainvoke(classification_messages)
            raw = extract_text(result.content).strip().lower().rstrip(".")
            candidate = raw.split()[0] if raw.split() else ""

            if candidate in INTENTS:
                logger.info(f"LLM router → {candidate}")
                return candidate

            if "relationship" in raw or "crm" in raw or "intelligence" in raw:
                return "relationship_intelligence"

            logger.warning(f"Router: unrecognised '{raw}', defaulting to portfolio_insights")
            return "portfolio_insights"

        except Exception as e:
            logger.error(f"LLM router error: {e}", exc_info=True)
            return "portfolio_insights"


# Module-level singleton shared across the orchestrator and graph.
router_agent = RouterAgent()
