# Generated by GitHub Copilot
"""UI route – serves the static HTML chat shell with cache-busted asset links."""
from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["ui"], include_in_schema=False)

_BASE_DIR = Path(__file__).resolve().parent.parent.parent
_STATIC_DIR = _BASE_DIR / "app" / "static"
_INDEX_HTML = _BASE_DIR / "app" / "templates" / "index.html"


def _asset_version() -> str:
    """Return a cache-bust token based on the newest static-file mtime."""
    candidates = [_STATIC_DIR / "app.js", _STATIC_DIR / "style.css"]
    latest = max((p.stat().st_mtime_ns for p in candidates if p.exists()), default=0)
    return str(latest)


@router.get("/", summary="Chat UI")
async def index() -> HTMLResponse:
    """Serve the Wealth Management Assistant chat UI."""
    html = _INDEX_HTML.read_text(encoding="utf-8")
    html = html.replace("{{ASSET_VERSION}}", _asset_version())
    return HTMLResponse(html, headers={"Cache-Control": "no-store, must-revalidate"})
