# Generated by GitHub Copilot
"""Initialise the MySQL memory database (tables for short & long-term memory).

Usage
-----
From the project root, with the virtualenv active::

    python -m scripts.init_memory_db

What it does
------------
1. Connects to the MySQL **server** (not a specific database) and runs
   ``CREATE DATABASE IF NOT EXISTS <MYSQL_DATABASE>`` so the schema exists.
2. Connects to that database and creates every memory table via
   SQLAlchemy ``Base.metadata.create_all`` (idempotent — never drops data).

Connection details come from the same settings used by the app
(``MYSQL_HOST`` / ``MYSQL_PORT`` / ``MYSQL_USER`` / ``MYSQL_PASSWORD`` /
``MYSQL_DATABASE``), configurable via environment variables or ``.env``.

Prefer pure SQL? Run ``data/memory/wealth_memory_mysql_ddl.sql`` instead.
"""

from __future__ import annotations

import sys
from urllib.parse import quote_plus

from sqlalchemy import create_engine, text

from app.config import settings


def _server_url() -> str:
    """SQLAlchemy URL pointing at the MySQL server (no database selected)."""
    password = quote_plus(settings.MYSQL_PASSWORD)
    return (
        f"mysql+pymysql://{settings.MYSQL_USER}:{password}"
        f"@{settings.MYSQL_HOST}:{settings.MYSQL_PORT}/?charset=utf8mb4"
    )


def create_database() -> None:
    """Create the target database if it does not already exist."""
    server_engine = create_engine(_server_url(), future=True)
    db_name = settings.MYSQL_DATABASE
    with server_engine.connect() as conn:
        conn.execute(
            text(
                f"CREATE DATABASE IF NOT EXISTS `{db_name}` "
                "CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
            )
        )
        conn.commit()
    server_engine.dispose()
    print(f"[init_memory_db] database ensured: {db_name}")


def create_tables() -> None:
    """Create all memory tables inside the target database."""
    # Imported here so create_database() can run even before the DB exists.
    from app.db.session import init_db

    init_db()
    print("[init_memory_db] tables ensured: chat_sessions, chat_messages, "
          "episodic_memory, semantic_memory, procedural_memory")


def main() -> int:
    print("[init_memory_db] connecting to MySQL at "
          f"{settings.MYSQL_HOST}:{settings.MYSQL_PORT} as {settings.MYSQL_USER}")
    try:
        create_database()
        create_tables()
    except Exception as e:  # pragma: no cover - depends on live DB
        print(f"[init_memory_db] FAILED: {type(e).__name__}: {e}", file=sys.stderr)
        print("[init_memory_db] Check MYSQL_* settings / that the MySQL server "
              "is running and reachable.", file=sys.stderr)
        return 1
    print("[init_memory_db] done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
