# Generated by GitHub Copilot
"""Rebuild and seed the MySQL memory tables from the legacy JSON files.

This loader (re)creates the memory schema and loads the existing JSON stores
into it via SQLAlchemy:

    data/memory/sessions.json          -> chat_sessions + chat_messages
    data/memory/long_term_memory.json  -> episodic_memory / semantic_memory /
                                          procedural_memory / client_preferences

Why it DROPs and recreates the tables
--------------------------------------
The schema gained a ``client_id`` column on ``chat_sessions`` and a new
``client_preferences`` table. ``create_all`` does not ALTER existing tables, so
the memory tables are dropped and rebuilt. This is safe: the two JSON files are
the source of truth and remain untouched, so the load is fully reproducible.

Columns not present in the JSON are filled automatically
--------------------------------------------------------
    * chat_sessions.client_id       = resolved from episodic memory (each
                                       episode carries both session_id and the
                                       owning client); falls back to 'unknown'.
    * semantic_memory.fact_hash      = sha256(lower(trim(fact)))
    * procedural_memory.pattern_hash = sha256(lower(trim(pattern)))
    * client_preferences.*           = derived per client (see _CURATED_PREFS)

Usage (from the project root, venv active)::

    python -m scripts.seed_from_json
"""

from __future__ import annotations

import hashlib
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy import delete

from app.config import settings
from app.db.models import (
    Base,
    ChatMessage,
    ChatSession,
    ClientPreference,
    EpisodicMemory,
    ProceduralMemory,
    SemanticMemory,
)
from app.db.session import engine, init_db, session_scope


# ── curated preferences per client (filled where JSON has no explicit column) ──
# Derived from each client's actual episodic/semantic content in the JSON.
# Tuple shape: (category, pref_key, pref_value, confidence, source)
_CURATED_PREFS: Dict[str, List[Tuple[str, str, str, float, str]]] = {
    "C001": [
        ("risk", "risk_tolerance", "moderate", 0.9, "explicit"),
        ("investment", "tax_saving_instrument", "ELSS", 0.9, "explicit"),
        ("investment", "sector_interest", "pharma", 0.7, "inferred"),
        ("communication", "preferred_channel", "in-person", 0.8, "inferred"),
        ("communication", "report_frequency", "quarterly", 0.6, "inferred"),
    ],
    "unknown": [
        ("risk", "risk_profile", "aggressive", 0.7, "inferred"),
        ("investment", "sector_interest", "pharma", 0.75, "explicit"),
        ("investment", "diversification_goal", "reduce IT/Financials concentration", 0.7, "inferred"),
    ],
}


# ── helpers ─────────────────────────────────────────────────────────────────────

def _hash(text: str) -> str:
    """SHA-256 of the normalised text — fills the *_hash dedup columns."""
    return hashlib.sha256(text.strip().lower().encode("utf-8")).hexdigest()


def _parse_dt(value: Optional[str]) -> datetime:
    """Parse an ISO timestamp into a naive UTC ``datetime``.

    Handles values with or without a timezone offset / microseconds. Falls
    back to "now" when the value is missing or unparseable.
    """
    if not value:
        return datetime.now(timezone.utc).replace(tzinfo=None)
    try:
        dt = datetime.fromisoformat(value)
    except ValueError:
        try:
            dt = datetime.fromisoformat(value.split(".")[0])
        except ValueError:
            return datetime.now(timezone.utc).replace(tzinfo=None)
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return dt


def _load_json(path: Path) -> Dict[str, Any]:
    """Load a JSON file, returning {} if it is missing or invalid."""
    if not path.exists():
        print(f"[seed] skip (not found): {path}")
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        print(f"[seed] WARNING could not read {path}: {e}")
        return {}


def _build_session_client_map(long_term: Dict[str, Any]) -> Dict[str, str]:
    """Map session_id -> client_id using episodic memory.

    Each episodic record carries both a ``session_id`` and lives under a client
    key, so it links a session to the client that owns it. A real client always
    wins over ``"unknown"`` when the same session appears under both.
    """
    mapping: Dict[str, str] = {}
    for client_id, bucket in long_term.items():
        if not isinstance(bucket, dict):
            continue
        for ep in bucket.get("episodic", []):
            sid = ep.get("session_id")
            if not sid:
                continue
            current = mapping.get(sid)
            if current is None or (current == "unknown" and client_id != "unknown"):
                mapping[sid] = client_id
    return mapping


# ── schema rebuild ──────────────────────────────────────────────────────────────

def reset_schema() -> None:
    """Drop and recreate all memory tables so the new schema is applied."""
    print("[seed] dropping + recreating memory tables (schema rebuild)...")
    Base.metadata.drop_all(bind=engine)
    init_db()


# ── short-term: sessions.json -> chat_sessions / chat_messages ─────────────────

def seed_short_term(session_client: Dict[str, str]) -> None:
    path = Path(settings.MEMORY_STORAGE_PATH)
    data = _load_json(path)
    if not data:
        return

    sessions = 0
    messages = 0
    with session_scope() as db:
        for session_id, info in data.items():
            if not isinstance(info, dict):
                continue
            created = _parse_dt(info.get("created_at"))
            updated = _parse_dt(info.get("last_updated"))
            client_id = session_client.get(session_id, "unknown")

            # Upsert the session row (stable PK = session_id).
            db.merge(
                ChatSession(
                    session_id=session_id,
                    client_id=client_id,
                    summary=info.get("summary"),
                    created_at=created,
                    last_updated=updated,
                )
            )
            db.flush()

            # Replace messages for this session so re-runs don't duplicate
            # (chat_messages.id is auto-increment, so we can't merge by PK).
            db.execute(
                delete(ChatMessage).where(ChatMessage.session_id == session_id)
            )
            for entry in info.get("history", []):
                role = entry.get("role", "")
                content = str(entry.get("content", ""))
                if not role or not content:
                    continue
                db.add(
                    ChatMessage(
                        session_id=session_id,
                        role=role,
                        content=content,
                        created_at=_parse_dt(entry.get("timestamp")),
                    )
                )
                messages += 1
            sessions += 1

    print(f"[seed] short-term: {sessions} sessions, {messages} messages")


# ── long-term: long_term_memory.json -> 4 tables ───────────────────────────────

def seed_long_term() -> None:
    path = Path(settings.LONG_TERM_MEMORY_PATH)
    data = _load_json(path)
    if not data:
        return

    n_epi = n_sem = n_proc = n_pref = 0
    with session_scope() as db:
        for client_id, bucket in data.items():
            if not isinstance(bucket, dict):
                continue

            # ── episodic ──
            for ep in bucket.get("episodic", []):
                db.merge(
                    EpisodicMemory(
                        id=ep.get("id") or str(uuid.uuid4()),
                        client_id=client_id,
                        session_id=ep.get("session_id", ""),
                        query=ep.get("query", ""),
                        answer=(ep.get("answer", "") or "")[:800],
                        intent=ep.get("intent", "general"),
                        confidence=float(ep.get("confidence", 1.0)),
                        created_at=_parse_dt(ep.get("timestamp")),
                    )
                )
                n_epi += 1

            # ── semantic (fill missing fact_hash) ──
            for sf in bucket.get("semantic", []):
                fact = (sf.get("fact", "") or "").strip()
                if not fact:
                    continue
                db.merge(
                    SemanticMemory(
                        id=sf.get("id") or str(uuid.uuid4()),
                        client_id=client_id,
                        fact=fact,
                        fact_hash=_hash(fact),
                        confidence=float(sf.get("confidence", 0.85)),
                        source_query=(sf.get("source_query", "") or "")[:300],
                        created_at=_parse_dt(sf.get("timestamp")),
                    )
                )
                n_sem += 1

            # ── procedural (fill missing pattern_hash) ──
            for pp in bucket.get("procedural", []):
                pattern = (pp.get("pattern", "") or "").strip()
                if not pattern:
                    continue
                db.merge(
                    ProceduralMemory(
                        id=pp.get("id") or str(uuid.uuid4()),
                        client_id=client_id,
                        pattern=pattern,
                        pattern_hash=_hash(pattern),
                        frequency=int(pp.get("frequency", 1)),
                        created_at=_parse_dt(pp.get("timestamp")),
                        last_seen=_parse_dt(pp.get("last_seen") or pp.get("timestamp")),
                    )
                )
                n_proc += 1

            # ── preferences (new table — derived/curated since JSON lacks them) ──
            for category, key, value, conf, source in _CURATED_PREFS.get(client_id, []):
                db.merge(
                    ClientPreference(
                        # Deterministic id so re-runs upsert instead of duplicate.
                        id=str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{client_id}:{key}")),
                        client_id=client_id,
                        category=category,
                        pref_key=key,
                        pref_value=value,
                        confidence=conf,
                        source=source,
                        created_at=datetime.now(timezone.utc).replace(tzinfo=None),
                        updated_at=datetime.now(timezone.utc).replace(tzinfo=None),
                    )
                )
                n_pref += 1

    print(
        f"[seed] long-term: {n_epi} episodic, {n_sem} semantic, "
        f"{n_proc} procedural, {n_pref} preferences"
    )


def main() -> int:
    long_term = _load_json(Path(settings.LONG_TERM_MEMORY_PATH))
    session_client = _build_session_client_map(long_term)
    try:
        reset_schema()
        seed_short_term(session_client)
        seed_long_term()
    except Exception as e:  # pragma: no cover - depends on live DB
        print(f"[seed] FAILED: {type(e).__name__}: {e}", file=sys.stderr)
        return 1
    print("[seed] done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
