# Generated by GitHub Copilot
"""End-to-end smoke test for the upgraded long-term memory pipeline.

Run from the project root with the virtualenv active::

    python -m scripts.test_memory_flow

What it verifies
----------------
1. **Embeddings + cosine** — paraphrases score higher than unrelated text.
2. **Storage** — a simulated multi-turn conversation is persisted (episodic +
   LLM-extracted semantic / procedural / preferences).
3. **Semantic retrieval** — a *differently worded* follow-up query retrieves the
   relevant past episode/fact via vector search (not keyword overlap).
4. **Update-in-place** — a changed preference / restated fact updates rather
   than duplicates.

Requires a reachable memory database and ``GOOGLE_API_KEY`` (for embeddings +
extraction). Steps that need an unavailable resource are reported and skipped.
The test uses a dedicated client id and deletes its rows on completion.
"""
from __future__ import annotations

from sqlalchemy import delete

from app.agents.memory import long_term_memory
from app.db.models import (
    ClientPreference,
    EpisodicMemory,
    ProceduralMemory,
    SemanticMemory,
)
from app.db.session import init_db, ping_db, session_scope
from app.repositories import long_term_repo
from app.services import embeddings

TEST_CLIENT = "TEST_MEM_CLIENT"


def _cleanup() -> None:
    with session_scope() as db:
        for model in (EpisodicMemory, SemanticMemory, ProceduralMemory, ClientPreference):
            db.execute(delete(model).where(model.client_id == TEST_CLIENT))


def test_embeddings() -> None:
    print("\n=== 1. Embeddings + cosine ===")
    base = embeddings.embed_text("What is my retirement savings plan?")
    if base is None:
        print("  SKIP: embeddings unavailable (no API key / network).")
        return
    near = embeddings.decode_embedding(
        embeddings.encode_embedding(embeddings.embed_text("How should I plan my pension?"))
    )
    far = embeddings.decode_embedding(
        embeddings.encode_embedding(embeddings.embed_text("What's the weather in Paris today?"))
    )
    scores = embeddings.cosine_rank(base, [near, far])
    print(f"  similar (pension) score : {scores[0]:.3f}")
    print(f"  unrelated (weather) score: {scores[1]:.3f}")
    assert scores[0] > scores[1], "paraphrase should outscore unrelated text"
    print("  PASS: semantic similarity ranks paraphrase above unrelated text.")


def test_storage_and_retrieval() -> None:
    print("\n=== 2. Storage (simulated conversation) ===")
    turns = [
        (
            "I'm 45 and want to retire by 60. I prefer low-risk investments and "
            "email updates.",
            "Noted. With a 15-year horizon and a low-risk preference, a "
            "conservative allocation tilted to bonds and index funds suits you. "
            "I'll send updates via email.",
            "portfolio_insights",
        ),
        (
            "Can you keep your answers short and to the point?",
            "Absolutely — I'll keep responses concise from now on.",
            "general",
        ),
        (
            "Actually, I've reconsidered — I'm now comfortable with moderate risk.",
            "Understood. I'll update your profile to a moderate risk tolerance and "
            "adjust suggested allocations accordingly.",
            "portfolio_insights",
        ),
    ]
    for q, a, intent in turns:
        long_term_memory.save_turn_facts(
            client_id=TEST_CLIENT, session_id="test-session", query=q, answer=a, intent=intent
        )
        print(f"  saved turn (intent={intent}): {q[:50]}...")

    print("\n=== 3. Stored long-term memory ===")
    mem = long_term_repo.get_client_memory(TEST_CLIENT)
    print(f"  episodic  : {len(mem['episodic'])} rows")
    print(f"  semantic  : {len(mem['semantic'])} facts")
    for f in mem["semantic"]:
        print(f"      - {f['fact']}")
    print(f"  procedural: {len(mem['procedural'])} patterns")
    for p in mem["procedural"]:
        print(f"      - {p['pattern']} (x{p['frequency']})")
    print(f"  preferences: {len(mem['preferences'])}")
    for pr in mem["preferences"]:
        print(f"      - {pr['key']} = {pr['value']} [{pr['category']}]")

    print("\n=== 4. Semantic retrieval (differently worded query) ===")
    probe = "When does the client plan to stop working and what is their appetite for volatility?"
    episodes = long_term_repo.search_episodic(TEST_CLIENT, probe, limit=2)
    print(f"  query: {probe}")
    for e in episodes:
        print(f"    episodic hit: {e['query'][:70]}")
    facts = long_term_repo.search_semantic(TEST_CLIENT, probe, limit=3)
    for f in facts:
        print(f"    semantic hit: {f['fact'][:80]}")

    print("\n=== 5. Full injected context block ===")
    ctx = long_term_memory.format_long_term_context(TEST_CLIENT, probe)
    print(ctx or "  (no context)")

    # Update-in-place check: risk preference should be the latest value only.
    risk_prefs = [p for p in mem["preferences"] if "risk" in p["key"].lower()]
    if risk_prefs:
        print(f"\n  risk preference current value: {risk_prefs[0]['value']} "
              "(should reflect the latest 'moderate' turn)")


def main() -> int:
    init_db()
    if not ping_db():
        print("DB unreachable — start MySQL (or set MEMORY_DATABASE_URL) and retry.")
        return 1
    _cleanup()
    try:
        test_embeddings()
        test_storage_and_retrieval()
    finally:
        _cleanup()
        print("\nCleaned up test client rows.")
    print("\nDONE.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
