# Generated by GitHub Copilot
"""Data-access package for the memory database.

Repositories are the **only** layer that talks to the ORM/session directly.
Service and agent modules (``app.services.memory`` and
``app.agents.memory.long_term_memory``) call these functions and never touch
SQLAlchemy themselves — keeping a clean separation between business logic and
persistence.
"""
